import { ASYNC, DB, ENTRY, type Problem } from "./types";

export const DATA_INFRA: Problem[] = [
  {
    slug: "leaderboard",
    title: "Game Leaderboard",
    tagline: "Design a real-time gaming leaderboard",
    difficulty: "Medium",
    category: "Data",
    askedAt: [],
    concepts: ["Redis sorted sets", "Top-N and rank queries", "Write-heavy counters", "Seasonal resets"],
    functional: ["Players submit scores", "Show the global top 100", "Show a player's own rank and nearby players", "Reset each season"],
    nonFunctional: ["Rank updates visible within a second", "Millions of players", "Reads spike at the end of matches"],
    estimates: [
      "10M DAU, ~10 matches each → ~1.2k score writes/sec",
      "Leaderboard reads ~3× writes, spiking after matches",
      "10M entries × ~50 bytes ≈ 500 MB — fits in one Redis sorted set (shard by region if needed)",
    ],
    api: [
      { method: "POST", path: "/scores", purpose: "Body { playerId, score } — server-validated from match results" },
      { method: "GET", path: "/leaderboard?top=100", purpose: "Top N players" },
      { method: "GET", path: "/leaderboard/players/{id}", purpose: "The player's rank plus 5 above and below" },
    ],
    dataModel: [
      {
        entity: "Ranking",
        store: "Redis sorted set",
        fields: "lb:{season} → member player_id, score",
        why: "ZADD, ZREVRANGE and ZREVRANK are all O(log N), which is exactly what top-N and 'my rank' need.",
      },
      {
        entity: "Player profile",
        store: "PostgreSQL",
        fields: "player_id, name, avatar, region",
        why: "Hydrates IDs into names. Cached, since profiles rarely change.",
      },
      {
        entity: "Score history",
        store: "Cassandra",
        fields: "player_id, match_id, score, ts",
        why: "Durable record to rebuild rankings or audit cheating.",
      },
    ],
    checkpoints: [
      {
        id: "entry",
        kind: "connection",
        title: "Clients enter via a load balancer",
        from: ["client"],
        to: ENTRY,
        hint: "Front door.",
        why: "Standard entry point.",
      },
      {
        id: "zset",
        kind: "component",
        title: "Sorted set for rankings",
        types: ["cache"],
        hint: "'What's my rank among 10M players?' — ORDER BY on every request?",
        why: "A Redis sorted set keeps members ordered by score, so rank and top-N queries are O(log N).",
      },
      {
        id: "svc-zset",
        kind: "connection",
        title: "Services read and write the sorted set",
        from: ["service"],
        to: ["cache"],
        hint: "Connect scoring and reading to the rankings.",
        why: "Score writes are ZADD, reads are ZREVRANGE and ZREVRANK.",
      },
      {
        id: "durable",
        kind: "component",
        title: "Durable score history",
        types: DB,
        hint: "Redis loses its data. Can you rebuild the leaderboard?",
        why: "Persist every score to a database so rankings can be rebuilt and audited.",
      },
      {
        id: "events",
        kind: "component",
        title: "Async score events",
        types: ASYNC,
        hint: "Archiving and anti-cheat shouldn't slow score submission.",
        why: "Publish score events to a stream for archiving and analytics off the hot path.",
      },
    ],
    solution: {
      nodes: [
        { id: "c", type: "client", label: "Players", col: 0, row: 1, note: "Submit scores after matches and check rankings." },
        { id: "lb", type: "load_balancer", label: "Load Balancer", col: 1, row: 1, note: "Splits writes and reads." },
        { id: "score", type: "service", label: "Score Service", col: 2, row: 0.4, note: "Validates results server-side, then ZADDs and publishes an event." },
        { id: "zset", type: "cache", label: "Redis Sorted Sets", col: 3, row: 1, note: "One sorted set per season (and per region). Rank queries are O(log N).", config: { replicas: 2 } },
        { id: "read", type: "service", label: "Leaderboard Service", col: 2, row: 1.7, note: "Top 100 and around-me queries, with names hydrated." },
        { id: "players", type: "sql_db", label: "Player Profiles", col: 3, row: 2.4, note: "Names and avatars." },
        { id: "events", type: "stream", label: "Score Events", col: 3, row: -0.2, note: "Every accepted score." },
        { id: "arch", type: "worker", label: "Archiver", col: 4, row: -0.2, note: "Persists history and feeds anti-cheat checks." },
        { id: "hist", type: "nosql_db", label: "Score History", col: 5, row: -0.2, note: "Durable record, used to rebuild the sorted set." },
        { id: "reset", type: "scheduler", label: "Season Reset", col: 4, row: 1.8, note: "Starts a new sorted set each season and archives the old one." },
      ],
      edges: [
        { from: "c", to: "lb" },
        { from: "lb", to: "score", ratio: 1 },
        { from: "lb", to: "read", ratio: 3 },
        { from: "score", to: "zset", label: "ZADD" },
        { from: "score", to: "events" },
        { from: "events", to: "arch" },
        { from: "arch", to: "hist" },
        { from: "read", to: "zset", label: "ZREVRANGE / RANK" },
        { from: "read", to: "players", label: "hydrate" },
        { from: "reset", to: "zset" },
      ],
    },
    decisions: [
      {
        q: "Why Redis sorted sets instead of SQL?",
        a: "SQL needs ORDER BY score with an index scan to compute rank (COUNT of higher scores), which gets slow at 10M rows under constant writes. A sorted set is a skip list designed for exactly these queries.",
      },
      {
        q: "What if Redis loses data?",
        a: "Use replicas and AOF persistence, and treat the durable score history as the source of truth: the sorted set can be rebuilt from it.",
      },
      {
        q: "Beyond one Redis instance?",
        a: "Shard by region or league (most leaderboards are scoped anyway), or keep exact top-K plus approximate ranks for the long tail.",
      },
    ],
    deepDives: [
      { q: "Ties?", a: "Encode a tiebreaker in the score (e.g. score × 10⁶ + (MAX_TS − ts)) so earlier achievers rank higher." },
      { q: "Friends leaderboard?", a: "Compute on read by fetching friends' scores (ZMSCORE) and sorting a small list, or keep per-user friend sorted sets if friend lists are big." },
      { q: "Cheating?", a: "Never accept scores straight from clients. Derive them from server-authoritative match results, and flag anomalies asynchronously." },
    ],
    mistakes: [
      "Computing rank with a COUNT(*) query per request.",
      "Trusting client-submitted scores.",
      "No durable copy, so a Redis failure loses the leaderboard.",
    ],
  },
  {
    slug: "metrics-monitoring",
    title: "Metrics & Monitoring",
    tagline: "Design Datadog / Prometheus",
    difficulty: "Hard",
    category: "Data",
    askedAt: [],
    concepts: ["High-throughput ingestion", "Time-series storage", "Downsampling / rollups", "Streaming alert evaluation", "Hot vs cold data"],
    functional: ["Agents send metrics (CPU, latency, counters) from every host", "Dashboards query metrics over time ranges", "Alert when a metric crosses a threshold"],
    nonFunctional: ["Ingest millions of points/sec", "Recent data queries in < 1 s", "Alerts fire within a minute", "Keep data for a year cheaply"],
    estimates: [
      "100k hosts × 100 metrics every 10 s ≈ 1M points/sec",
      "~16 bytes/point compressed → ~1.4 TB/day raw, reduced heavily by rollups",
      "Dashboard queries: ~1k/sec, mostly for the last hour",
    ],
    api: [
      { method: "POST", path: "/ingest", purpose: "Batched points { metric, tags, ts, value }[]" },
      { method: "GET", path: "/query?metric=&tags=&from=&to=&step=", purpose: "Time series for a dashboard" },
      { method: "POST", path: "/alerts", purpose: "Define an alert rule, e.g. avg(latency) > 500 for 5m" },
    ],
    dataModel: [
      {
        entity: "Data point",
        store: "Time-series DB (e.g. InfluxDB, Cassandra-based)",
        fields: "series_id (metric + tags) → (ts, value) blocks",
        why: "Append-only, time-ordered data compresses extremely well (delta and Gorilla encoding) and is queried by time range.",
      },
      {
        entity: "Rollup",
        store: "Same TSDB, separate tables",
        fields: "series_id, 1m/1h buckets → min, max, avg, count",
        why: "Year-long charts read hourly rollups, not billions of raw points.",
      },
    ],
    checkpoints: [
      {
        id: "entry",
        kind: "connection",
        title: "Agents send through a load balancer",
        from: ["client"],
        to: ENTRY,
        hint: "100k hosts push data. Where does it land?",
        why: "Stateless ingestion servers behind a load balancer accept batched points.",
      },
      {
        id: "stream",
        kind: "component",
        title: "Stream buffers ingestion",
        types: ASYNC,
        hint: "1M points/sec, and a slow database write shouldn't make agents drop data.",
        why: "Kafka absorbs the firehose and decouples ingestion from storage and alerting.",
      },
      {
        id: "consumers",
        kind: "connection",
        title: "Consumers process the stream",
        from: ASYNC,
        to: ["worker"],
        hint: "Who writes the data and evaluates alerts?",
        why: "Separate consumer groups write rollups to the TSDB and evaluate alert rules on the live stream.",
      },
      {
        id: "tsdb",
        kind: "component",
        title: "Time-series database",
        types: DB,
        hint: "Which store handles time-ordered, append-only data?",
        why: "A TSDB compresses and indexes by series and time.",
      },
      {
        id: "write",
        kind: "connection",
        title: "Workers write to the TSDB",
        from: ["worker"],
        to: DB,
        hint: "Connect the pipeline to storage.",
        why: "Rollup workers batch-write raw points and downsampled aggregates.",
      },
      {
        id: "qcache",
        kind: "component",
        title: "Query cache",
        types: ["cache"],
        hint: "Fifty engineers open the same dashboard during an incident.",
        why: "Cache query results for dashboards, so repeated panels don't rescan the TSDB.",
      },
    ],
    solution: {
      nodes: [
        { id: "agents", type: "client", label: "Host Agents", col: 0, row: 0.8, note: "Batch metrics locally and push every 10 s." },
        { id: "dash", type: "client", label: "Dashboards", col: 0, row: 2.4, note: "Engineers querying charts, especially during incidents." },
        { id: "lb", type: "load_balancer", label: "Ingest LB", col: 1, row: 0.8, note: "Spreads agent traffic." },
        { id: "ingest", type: "service", label: "Ingestion API", col: 2, row: 0.8, note: "Validates and tags batches, then publishes them to Kafka. Stateless and fast." },
        { id: "kafka", type: "stream", label: "Metrics Stream", col: 3, row: 0.8, note: "Partitioned by series, with hours of buffer." },
        { id: "roll", type: "worker", label: "Rollup Writers", col: 4, row: 0.2, note: "Write raw points plus 1-minute and 1-hour rollups in batches." },
        { id: "alert", type: "worker", label: "Alert Evaluator", col: 4, row: 1.4, note: "Evaluate rules over sliding windows on the live stream." },
        { id: "notif", type: "queue", label: "Alert Notifications", col: 5, row: 1.4, note: "Pager, Slack and email fan-out." },
        { id: "pager", type: "worker", label: "Notifier", col: 6, row: 1.4, note: "Delivers alerts to PagerDuty, Slack and email, deduplicating repeats." },
        { id: "tsdb", type: "nosql_db", label: "Time-Series DB", col: 5, row: 0.2, note: "Compressed series blocks, with cold data moved to object storage." },
        { id: "query", type: "service", label: "Query API", col: 2, row: 2.4, note: "Picks the right resolution (raw vs rollup) for the time range." },
        { id: "qc", type: "cache", label: "Query Cache", col: 3, row: 2.4, note: "Recent dashboard panel results." },
      ],
      edges: [
        { from: "agents", to: "lb" },
        { from: "lb", to: "ingest" },
        { from: "ingest", to: "kafka" },
        { from: "kafka", to: "roll" },
        { from: "kafka", to: "alert" },
        { from: "roll", to: "tsdb", label: "batched writes" },
        { from: "alert", to: "notif", label: "firing", ratio: 0.01 },
        { from: "notif", to: "pager" },
        { from: "dash", to: "query" },
        { from: "query", to: "qc" },
        { from: "query", to: "tsdb", label: "miss" },
      ],
    },
    decisions: [
      {
        q: "Why a TSDB rather than a general database?",
        a: "Metrics are append-only, time-ordered, and queried by range and series. TSDBs exploit that with columnar compression (often 10× or more), time partitioning, and cheap retention by dropping old partitions.",
      },
      {
        q: "Why Kafka in the middle?",
        a: "It decouples ingestion from storage (a slow database won't make agents drop data), lets several consumers (storage, alerts, anomaly detection) read the same stream, and allows replay after bugs.",
      },
      {
        q: "Why downsample?",
        a: "A one-year chart can't render billions of points anyway. Storing 1-minute and 1-hour rollups cuts both storage and query time dramatically.",
      },
    ],
    deepDives: [
      { q: "Push or pull?", a: "Prometheus pulls (scrapes targets), which is simple and gives up/down detection for free. Datadog agents push, which works through firewalls and for short-lived jobs. Both are valid; say why you picked one." },
      { q: "High cardinality?", a: "Tags like user_id explode the number of series. Limit tag cardinality, or route high-cardinality data to logs and traces instead." },
      { q: "Alerting reliability?", a: "Run alert evaluators in redundant pairs, and dedupe notifications, so one evaluator crash doesn't silence alerts." },
    ],
    mistakes: [
      "Writing each point synchronously to a relational database.",
      "Querying raw points for long time ranges.",
      "Evaluating alerts by polling the database with heavy queries every few seconds.",
    ],
  },
  {
    slug: "job-scheduler",
    title: "Distributed Job Scheduler",
    tagline: "Design cron at scale / Airflow",
    difficulty: "Medium",
    category: "Infrastructure",
    askedAt: [],
    concepts: ["Time-based scheduling", "Work queues", "At-least-once execution + idempotency", "Leases & retries", "Leader election"],
    functional: ["Schedule one-off or recurring (cron) jobs", "Run jobs on a worker fleet", "Retry failures and show status and logs"],
    nonFunctional: ["Jobs start within seconds of their scheduled time", "A job must not be silently skipped", "Workers can fail mid-job"],
    estimates: [
      "10M scheduled jobs, ~1k due per second at peak (top of the hour)",
      "Job runtimes: seconds to hours",
      "Status updates ≈ 3 per job run",
    ],
    api: [
      { method: "POST", path: "/jobs", purpose: "Body { schedule (cron or at), payload, retries, timeout } → jobId" },
      { method: "GET", path: "/jobs/{id}/runs", purpose: "Run history and status" },
      { method: "DELETE", path: "/jobs/{id}", purpose: "Cancel a job" },
    ],
    dataModel: [
      {
        entity: "Job",
        store: "PostgreSQL",
        fields: "job_id, schedule, next_run_at (indexed), payload, owner",
        why: "The scheduler polls 'WHERE next_run_at <= now' through an index. Relational and transactional.",
      },
      {
        entity: "Run",
        store: "PostgreSQL / Cassandra",
        fields: "run_id, job_id, status, attempt, lease_until, started_at, finished_at",
        why: "Tracks each execution, and leases let a stuck run be reclaimed.",
      },
    ],
    checkpoints: [
      {
        id: "entry",
        kind: "connection",
        title: "Users reach the API via a load balancer",
        from: ["client"],
        to: ENTRY,
        hint: "Front door for creating jobs.",
        why: "A stateless API behind a load balancer.",
      },
      {
        id: "sched",
        kind: "component",
        title: "A scheduler finds due jobs",
        types: ["scheduler"],
        hint: "Something has to notice 'it's 9:00 — these jobs are due'.",
        why: "A leader-elected scheduler polls for due jobs (next_run_at ≤ now) every second and enqueues them.",
      },
      {
        id: "queue",
        kind: "component",
        title: "Ready queue",
        types: ASYNC,
        hint: "Due jobs pile up at the top of the hour. Where do they wait?",
        why: "A queue decouples 'this is due' from 'a worker is free' and absorbs the bursts.",
      },
      {
        id: "enqueue",
        kind: "connection",
        title: "Scheduler enqueues due jobs",
        from: ["scheduler"],
        to: ASYNC,
        hint: "Connect the scheduler to the queue.",
        why: "Due jobs are pushed to the ready queue with their run IDs.",
      },
      {
        id: "workers",
        kind: "connection",
        title: "Workers execute jobs",
        from: ASYNC,
        to: ["worker"],
        hint: "Who runs them?",
        why: "Workers lease a job, run it, heartbeat, and report status. An expired lease means another worker retries it.",
      },
      {
        id: "db",
        kind: "component",
        title: "Job and run store",
        types: DB,
        hint: "Where do schedules and run history live?",
        why: "A database with an index on next_run_at, plus run records with leases.",
      },
    ],
    solution: {
      nodes: [
        { id: "c", type: "client", label: "Users & Services", col: 0, row: 1, note: "Create, list and cancel jobs." },
        { id: "lb", type: "load_balancer", label: "Load Balancer", col: 1, row: 1, note: "Front door." },
        { id: "api", type: "service", label: "Job API", col: 2, row: 1, note: "CRUD for jobs, and computes next_run_at from the cron expression." },
        { id: "db", type: "sql_db", label: "Jobs & Runs", col: 3, row: 0.8, note: "Indexed on next_run_at. Run records carry leases.", config: { replicas: 2 } },
        { id: "sched", type: "scheduler", label: "Scheduler (Leader)", col: 2, row: 2.4, note: "Every second, claims due jobs and enqueues them. A standby takes over if it dies.", config: { sourceRps: 50 } },
        { id: "q", type: "queue", label: "Ready Queue", col: 3, row: 2.4, note: "Due jobs waiting for a free worker." },
        { id: "w", type: "worker", label: "Workers", col: 4, row: 2.4, note: "Lease, run, heartbeat and report. A lost lease means someone else retries.", config: { replicas: 4, latencyMs: 1000 } },
        { id: "logs", type: "object_storage", label: "Job Logs", col: 5, row: 2.4, note: "stdout and stderr of each run." },
      ],
      edges: [
        { from: "c", to: "lb" },
        { from: "lb", to: "api" },
        { from: "api", to: "db" },
        { from: "sched", to: "db", label: "claim due jobs" },
        { from: "sched", to: "q", label: "enqueue" },
        { from: "q", to: "w" },
        { from: "w", to: "db", label: "status" },
        { from: "w", to: "logs" },
      ],
    },
    decisions: [
      {
        q: "How do you avoid running a job twice?",
        a: "You can't fully guarantee it (a worker can finish and then crash before acking), so aim for at-least-once and make jobs idempotent. The scheduler claims jobs with a transaction (UPDATE … WHERE next_run_at <= now RETURNING), so it doesn't enqueue duplicates itself.",
      },
      {
        q: "Why leases?",
        a: "If a worker dies mid-job, its lease expires and the run becomes claimable again. Without leases, crashed jobs stay 'running' forever.",
      },
      {
        q: "Why a separate scheduler and workers?",
        a: "Finding due jobs is light and time-critical; running them is heavy and variable. Separating them keeps scheduling on time even when workers are saturated.",
      },
    ],
    deepDives: [
      { q: "The top-of-the-hour spike?", a: "Many jobs are scheduled at :00. Enqueue ahead of time (a few seconds early, with a delay) and scale workers, or add jitter to non-critical jobs." },
      { q: "Scheduler scale?", a: "Partition jobs by hash across several schedulers, each owning a partition, with leader election per partition." },
      { q: "Dependencies (DAGs)?", a: "Airflow-style workflows: a job becomes due when its upstream runs succeed, tracked in a run graph." },
    ],
    mistakes: [
      "Running cron on a single machine, which is a single point of failure.",
      "No leases, so crashed jobs never retry.",
      "Polling with a full table scan instead of an index on next_run_at.",
    ],
  },
  {
    slug: "online-judge",
    title: "Online Judge",
    tagline: "Design LeetCode",
    difficulty: "Medium",
    category: "Infrastructure",
    askedAt: [],
    concepts: ["Sandboxed code execution", "Async job queue", "Burst handling (contests)", "Result polling / push"],
    functional: ["Browse problems", "Submit code in many languages", "Run it against hidden tests and return a verdict", "Contest leaderboards"],
    nonFunctional: ["Untrusted code must be isolated", "Verdicts in a few seconds", "Handle contest spikes (thousands submitting at once)"],
    estimates: [
      "Normal: ~50 submissions/sec; contests: 10× bursts",
      "Each run takes 1–10 s of CPU in a sandbox",
      "Problem pages are read ~20× more than code is submitted",
    ],
    api: [
      { method: "GET", path: "/problems/{slug}", purpose: "Problem statement and examples (CDN-cacheable)" },
      { method: "POST", path: "/submissions", purpose: "Body { problemId, language, code } → submissionId, queued" },
      { method: "GET", path: "/submissions/{id}", purpose: "Poll for the verdict (or receive it via WebSocket)" },
    ],
    dataModel: [
      {
        entity: "Problem",
        store: "PostgreSQL + cache",
        fields: "id, slug, statement, limits, test_suite_key",
        why: "Rarely written and read constantly, so it's cached. Tests live in object storage.",
      },
      {
        entity: "Submission",
        store: "PostgreSQL",
        fields: "id, user_id, problem_id, language, status, verdict, runtime_ms",
        why: "Status transitions plus per-user and per-problem queries.",
      },
    ],
    checkpoints: [
      {
        id: "entry",
        kind: "connection",
        title: "Clients enter via a load balancer",
        from: ["client"],
        to: ENTRY,
        hint: "Front door.",
        why: "Standard entry.",
      },
      {
        id: "queue",
        kind: "component",
        title: "Submission queue",
        types: ASYNC,
        hint: "Running code takes seconds, and a contest brings thousands at once. Execute inside the web request?",
        why: "Enqueue submissions. The API returns immediately, and the queue absorbs contest bursts.",
      },
      {
        id: "runners",
        kind: "connection",
        title: "Sandboxed runners consume the queue",
        from: ASYNC,
        to: ["worker"],
        hint: "Where does untrusted code actually run?",
        why: "Isolated runners (containers or microVMs with CPU, memory and network limits) execute code against the tests.",
      },
      {
        id: "db",
        kind: "component",
        title: "Submissions and problems store",
        types: DB,
        hint: "Where do verdicts and history live?",
        why: "A relational database stores problems and submission results.",
      },
      {
        id: "cache",
        kind: "component",
        title: "Cache for problem pages",
        types: ["cache", "cdn"],
        hint: "Everyone in a contest opens the same four problems.",
        why: "Cache problem statements (and put them behind a CDN) so reads don't hit the database.",
      },
    ],
    solution: {
      nodes: [
        { id: "c", type: "client", label: "Coders", col: 0, row: 1.5, note: "Mostly reading problems; sometimes submitting." },
        { id: "cdn", type: "cdn", label: "CDN", col: 1, row: 0, note: "Static assets and public problem pages." },
        { id: "lb", type: "load_balancer", label: "Load Balancer", col: 1, row: 1.5, note: "Routes reads and submissions." },
        { id: "prob", type: "service", label: "Problem Service", col: 2, row: 0.8, note: "Problem statements and examples." },
        { id: "pc", type: "cache", label: "Problem Cache", col: 3, row: 0.2, note: "Hot problem statements, especially during contests." },
        { id: "db", type: "sql_db", label: "Problems & Submissions", col: 4, row: 1.2, note: "Statements, submissions and verdicts.", config: { replicas: 2 } },
        { id: "sub", type: "service", label: "Submission Service", col: 2, row: 2.3, note: "Stores the submission as queued and enqueues a run job." },
        { id: "q", type: "queue", label: "Judge Queue", col: 3, row: 2.3, note: "Absorbs contest bursts. Priority lanes for contests." },
        { id: "run", type: "worker", label: "Sandboxed Runners", col: 4, row: 2.3, note: "Isolated containers with CPU, memory and time limits and no network. Compile, run tests, report the verdict.", config: { replicas: 10, capacity: 20, latencyMs: 2000 } },
      ],
      edges: [
        { from: "c", to: "cdn", label: "static" },
        { from: "c", to: "lb" },
        { from: "lb", to: "prob", ratio: 9 },
        { from: "lb", to: "sub", ratio: 1 },
        { from: "prob", to: "pc" },
        { from: "prob", to: "db", label: "miss" },
        { from: "sub", to: "db", label: "record" },
        { from: "sub", to: "q", label: "enqueue" },
        { from: "q", to: "run" },
        { from: "run", to: "db", label: "verdict" },
      ],
    },
    decisions: [
      {
        q: "Why a queue instead of running code in the request?",
        a: "Execution takes seconds and CPU is scarce. A queue returns instantly, smooths contest spikes, and lets runner capacity scale separately. Clients poll or get pushed the verdict.",
      },
      {
        q: "How do you isolate untrusted code?",
        a: "Run each submission in a locked-down container or microVM (e.g. gVisor, Firecracker) with no network, limited CPU, memory and time, a read-only filesystem, and seccomp filters.",
      },
      {
        q: "How do you handle contest bursts?",
        a: "Autoscale runners from queue depth, give contest submissions a priority lane, and pre-warm runner pools before contests start.",
      },
    ],
    deepDives: [
      { q: "Verdict delivery?", a: "Poll every second (simple), or push over WebSocket or SSE when the runner writes the result." },
      { q: "Test data?", a: "Keep hidden tests in object storage, cached on runner nodes. Never send them to clients." },
      { q: "Contest leaderboard?", a: "A Redis sorted set updated when a submission is accepted." },
    ],
    mistakes: [
      "Executing user code on the web servers.",
      "No resource limits, so one infinite loop starves the fleet.",
      "Synchronous submissions that time out during contests.",
    ],
  },
  {
    slug: "top-k-trending",
    title: "Top-K Trending",
    tagline: "Design YouTube's top-K most viewed videos",
    difficulty: "Hard",
    category: "Data",
    askedAt: [],
    concepts: ["Stream processing", "Windowed aggregation", "Count-min sketch / approximate counting", "Heavy hitters", "Precomputed results"],
    functional: ["Track view events", "Return the top K most viewed videos for the last hour, day and all time", "Results update every few minutes"],
    nonFunctional: ["Ingest ~1M view events/sec", "Top-K queries in < 50 ms", "Approximate counts are acceptable"],
    estimates: [
      "1M views/sec at peak",
      "Hundreds of millions of distinct videos — exact counters for all is a lot of memory",
      "Top-K reads are cheap if precomputed: ~1k/sec",
    ],
    api: [
      { method: "POST", path: "(internal) /views", purpose: "View event { videoId, userId, ts }" },
      { method: "GET", path: "/trending?window=1h&k=100", purpose: "Precomputed top K for a window" },
    ],
    dataModel: [
      {
        entity: "Window counts",
        store: "Stream processor state (Flink)",
        fields: "count-min sketch + min-heap of top K per window per partition",
        why: "Sketches count with bounded memory, and the heap tracks candidates cheaply.",
      },
      {
        entity: "Top-K result",
        store: "Redis",
        fields: "trending:{window} → sorted list of (video_id, count)",
        why: "Reads are a single key lookup.",
      },
      {
        entity: "Count archive",
        store: "Cassandra / warehouse",
        fields: "video_id, window, count",
        why: "Exact batch recounts and long-term analytics.",
      },
    ],
    checkpoints: [
      {
        id: "entry",
        kind: "connection",
        title: "Events enter via a load balancer",
        from: ["client"],
        to: ENTRY,
        hint: "Front door for view events.",
        why: "Stateless ingest servers behind a load balancer.",
      },
      {
        id: "stream",
        kind: "component",
        title: "Event stream",
        types: ASYNC,
        hint: "1M events/sec — increment database counters directly?",
        why: "Views go into a partitioned stream, and aggregation happens downstream.",
      },
      {
        id: "agg",
        kind: "connection",
        title: "Stream aggregators count per window",
        from: ASYNC,
        to: ["worker"],
        hint: "What turns raw events into counts?",
        why: "Stream processors keep windowed counts (sketches plus heaps) per partition, then merge them into a global top K.",
      },
      {
        id: "serve",
        kind: "component",
        title: "Precomputed top-K cache",
        types: ["cache"],
        hint: "Compute the top K on every read?",
        why: "Aggregators periodically write the top K per window to Redis, and reads just fetch it.",
      },
      {
        id: "publish",
        kind: "connection",
        title: "Aggregators publish results",
        from: ["worker"],
        to: ["cache"],
        hint: "Connect the aggregation to serving.",
        why: "Every minute, merged top-K lists are written to the cache.",
      },
    ],
    solution: {
      nodes: [
        { id: "c", type: "client", label: "Viewers", col: 0, row: 1, note: "Every play emits a view event; some load the trending page." },
        { id: "lb", type: "load_balancer", label: "Load Balancer", col: 1, row: 1, note: "Routes view ingest and trending reads." },
        { id: "ing", type: "service", label: "View Ingest", col: 2, row: 0.6, note: "Validates events and publishes them to Kafka, partitioned by video ID." },
        { id: "k", type: "stream", label: "View Events", col: 3, row: 0.6, note: "Partitioned by video ID, so each video is counted in one place." },
        { id: "agg", type: "worker", label: "Stream Aggregators", col: 4, row: 0.6, note: "Count-min sketch plus a top-K heap per window, merged across partitions every minute.", config: { replicas: 6 } },
        { id: "top", type: "cache", label: "Top-K Results", col: 5, row: 1.4, note: "trending:{window} lists, read directly by the API." },
        { id: "arch", type: "nosql_db", label: "Count Archive", col: 5, row: 0, note: "Exact counts from nightly batch jobs." },
        { id: "api", type: "service", label: "Trending API", col: 2, row: 2, note: "Serves precomputed lists." },
      ],
      edges: [
        { from: "c", to: "lb" },
        { from: "lb", to: "ing", ratio: 9 },
        { from: "lb", to: "api", ratio: 1 },
        { from: "ing", to: "k" },
        { from: "k", to: "agg" },
        { from: "agg", to: "top", label: "publish top K", ratio: 0.01 },
        { from: "agg", to: "arch", label: "window counts", ratio: 0.1 },
        { from: "api", to: "top" },
      ],
    },
    decisions: [
      {
        q: "Why not a counter per video in the database?",
        a: "A million increments a second on hot rows means lock contention and huge write load. Aggregating in a stream processor batches millions of events into periodic updates.",
      },
      {
        q: "Why a count-min sketch?",
        a: "Exact counts for hundreds of millions of videos take a lot of memory. A sketch estimates counts in fixed memory with small overestimates, and a heap keeps just the top candidates.",
      },
      {
        q: "Why partition by video ID?",
        a: "All events for a video land on one aggregator, so its count is local. Each partition emits its local top K, and a merge step combines them.",
      },
    ],
    deepDives: [
      { q: "Exactness?", a: "Lambda-style: the fast approximate stream path, plus a nightly batch job that recomputes exact counts and corrects the results." },
      { q: "Sliding windows?", a: "Keep per-minute buckets and sum the last 60 for the hour (subtract the expiring bucket), rather than recounting from scratch." },
      { q: "Hot partitions?", a: "A viral video overloads one partition. Pre-aggregate at the ingest servers (local counts every second) before publishing." },
    ],
    mistakes: [
      "UPDATE views = views + 1 per event.",
      "Sorting all videos by count on each request.",
      "Forgetting to merge per-partition top-K lists into a global top K.",
    ],
  },
  {
    slug: "ad-click-aggregator",
    title: "Ad Click Aggregator",
    tagline: "Design ad click aggregation for Google AdSense",
    difficulty: "Hard",
    category: "Data",
    askedAt: [],
    concepts: ["Click tracking redirects", "Deduplication / idempotency", "Stream aggregation (Flink)", "OLAP storage", "Batch reconciliation"],
    functional: ["Record clicks on ads, then redirect users to the advertiser", "Advertisers query click counts per ad per minute", "Counts must be accurate enough to bill"],
    nonFunctional: ["Handle ~10k clicks/sec, peaking higher", "Redirect latency < 100 ms", "No double counting; results within minutes"],
    estimates: [
      "10k clicks/sec ≈ 860M/day",
      "Per-minute aggregates: 10M ads × 1,440 minutes — mostly sparse",
      "Raw clicks ≈ 100 bytes → ~86 GB/day archived",
    ],
    api: [
      { method: "GET", path: "/click?ad={id}&imp={impressionId}", purpose: "Record the click and 302 redirect to the advertiser" },
      { method: "GET", path: "/ads/{id}/metrics?from=&to=&granularity=1m", purpose: "Aggregated clicks for dashboards" },
    ],
    dataModel: [
      {
        entity: "Click event",
        store: "Kafka → S3 archive",
        fields: "click_id, impression_id, ad_id, user_id, ts",
        why: "An immutable event stream, replayable for reprocessing and audits.",
      },
      {
        entity: "Aggregate",
        store: "OLAP (Druid / ClickHouse / Pinot)",
        fields: "ad_id, minute → clicks, unique_users",
        why: "Fast slice-and-dice queries over time and dimensions for dashboards.",
      },
    ],
    checkpoints: [
      {
        id: "entry",
        kind: "connection",
        title: "Clicks enter via a load balancer",
        from: ["client"],
        to: ENTRY,
        hint: "Front door for click redirects.",
        why: "Stateless click trackers behind a load balancer.",
      },
      {
        id: "dedupe",
        kind: "component",
        title: "Deduplication",
        types: ["cache"],
        hint: "Users double-click and bots replay. Billing on raw clicks overcharges advertisers.",
        why: "Check each impression or click ID against a short-TTL dedupe store before counting.",
      },
      {
        id: "stream",
        kind: "component",
        title: "Click stream",
        types: ASYNC,
        hint: "Should the redirect wait for aggregation?",
        why: "Log the click to Kafka and redirect immediately. Aggregation happens downstream.",
      },
      {
        id: "agg",
        kind: "connection",
        title: "Stream aggregation",
        from: ASYNC,
        to: ["worker"],
        hint: "Who turns clicks into per-minute counts?",
        why: "A stream processor (Flink) aggregates by ad and minute with exactly-once state.",
      },
      {
        id: "olap",
        kind: "component",
        title: "Analytics store",
        types: DB,
        hint: "Advertisers slice clicks by ad, time and region.",
        why: "An OLAP store serves fast aggregated queries.",
      },
      {
        id: "write",
        kind: "connection",
        title: "Aggregates written to the store",
        from: ["worker"],
        to: DB,
        hint: "Connect aggregation to storage.",
        why: "Aggregators flush per-minute results to the OLAP store.",
      },
    ],
    solution: {
      nodes: [
        { id: "c", type: "client", label: "Users Clicking Ads", col: 0, row: 1, note: "Each click hits the tracker, then redirects to the advertiser." },
        { id: "adv", type: "client", label: "Advertisers", col: 0, row: 2.6, note: "Query dashboards." },
        { id: "lb", type: "load_balancer", label: "Load Balancer", col: 1, row: 1, note: "Spreads click traffic." },
        { id: "track", type: "service", label: "Click Tracker", col: 2, row: 1, note: "Dedupes, logs the click to Kafka, and returns a 302 to the advertiser within milliseconds." },
        { id: "dd", type: "cache", label: "Dedupe Store", col: 3, row: 0, note: "Recent impression IDs with a TTL, via SET NX." },
        { id: "k", type: "stream", label: "Click Stream", col: 3, row: 1, note: "Durable, replayable log of clicks." },
        { id: "flink", type: "worker", label: "Stream Aggregators", col: 4, row: 0.6, note: "Count clicks per ad per minute with checkpointed, exactly-once state.", config: { replicas: 6 } },
        { id: "archive", type: "worker", label: "Archiver", col: 4, row: 1.6, note: "Writes raw clicks to object storage for reconciliation." },
        { id: "raw", type: "object_storage", label: "Raw Click Archive", col: 5, row: 1.6, note: "Source for nightly batch recounts." },
        { id: "olap", type: "nosql_db", label: "OLAP Store", col: 5, row: 0.6, note: "Per-minute aggregates, fast to slice.", config: { replicas: 3 } },
        { id: "recon", type: "scheduler", label: "Nightly Reconciliation", col: 6, row: 1.1, note: "Recounts from the raw archive and fixes any drift before billing." },
        { id: "rep", type: "service", label: "Reporting API", col: 2, row: 2.6, note: "Serves advertiser dashboards." },
      ],
      edges: [
        { from: "c", to: "lb" },
        { from: "lb", to: "track" },
        { from: "track", to: "dd", label: "dedupe" },
        { from: "track", to: "k", label: "log click" },
        { from: "k", to: "flink" },
        { from: "k", to: "archive" },
        { from: "flink", to: "olap", label: "per-minute counts", ratio: 0.1 },
        { from: "archive", to: "raw" },
        { from: "recon", to: "olap" },
        { from: "adv", to: "rep" },
        { from: "rep", to: "olap" },
      ],
    },
    decisions: [
      {
        q: "Why not write each click to the database?",
        a: "10k writes/sec of counter updates on hot ads causes contention, and couples the redirect's latency to the database. Streaming and aggregating turns millions of events into a few thousand rows per minute.",
      },
      {
        q: "How do you avoid double counting?",
        a: "Dedupe on impression or click ID at the tracker (a short-TTL store), and use a stream processor with exactly-once state (checkpoints plus transactional sinks) so replays don't recount.",
      },
      {
        q: "Why keep the raw clicks?",
        a: "Billing needs to be right. A nightly batch recount from the immutable archive (the Lambda architecture) catches anything the streaming path got wrong.",
      },
    ],
    deepDives: [
      { q: "Hot ads?", a: "A Super Bowl ad overloads one partition. Salt the partition key (ad_id + random suffix) and merge the partial counts." },
      { q: "Late events?", a: "Use event-time windows with watermarks and allow late updates for a few minutes, then let batch reconciliation fix the rest." },
      { q: "Fraud?", a: "Score clicks for bot patterns (IP, rate, user agent) asynchronously, and exclude flagged clicks from billing aggregates." },
    ],
    mistakes: [
      "Making the user wait for aggregation before redirecting.",
      "Counting raw clicks without deduplication.",
      "No raw archive, so mistakes can't be recomputed.",
    ],
  },
];
