import { ASYNC, DB, ENTRY, type Problem } from "./types";

export const SEARCH_COMMERCE: Problem[] = [
  {
    slug: "typeahead",
    title: "Search Autocomplete",
    tagline: "Design Google's typeahead suggestions",
    difficulty: "Medium",
    category: "Search",
    askedAt: ["Google"],
    concepts: ["Tries / prefix indexes", "Precomputed top-K", "Aggressive caching", "Offline aggregation pipeline"],
    functional: ["Suggest the top 5–10 completions as the user types", "Rank by popularity", "Reflect trending queries within hours"],
    nonFunctional: ["< 100 ms per keystroke, end to end", "Very high read volume (one request per keystroke)", "Suggestions can be slightly stale"],
    estimates: [
      "5B searches/day × ~6 keystrokes ≈ 350k suggestion requests/sec",
      "Top 10 for every prefix up to 20 chars of popular queries ≈ tens of GB — fits in memory across shards",
      "Query logs: 5B/day, aggregated hourly or daily",
    ],
    api: [
      { method: "GET", path: "/suggest?q={prefix}&limit=10", purpose: "Returns ranked completions; cacheable per prefix" },
      { method: "POST", path: "(internal) /log", purpose: "Completed searches flow into the aggregation pipeline" },
    ],
    dataModel: [
      {
        entity: "Prefix → top-K",
        store: "In-memory trie / Redis (sharded by prefix)",
        fields: "prefix → [(query, score)] × 10",
        why: "Precomputing the answer for each prefix turns a read into one lookup instead of a tree walk plus sort.",
      },
      {
        entity: "Query counts",
        store: "Data warehouse / object storage",
        fields: "query, count, window",
        why: "Offline aggregation of billions of log lines rebuilds the index periodically.",
      },
    ],
    checkpoints: [
      {
        id: "entry",
        kind: "connection",
        title: "Requests enter via a load balancer",
        from: ["client"],
        to: ENTRY,
        hint: "Front door first.",
        why: "Suggestion servers are stateless behind a load balancer.",
      },
      {
        id: "cache",
        kind: "component",
        title: "Cache of hot prefixes",
        types: ["cache", "cdn"],
        hint: "'a', 'am', 'ama'… a handful of prefixes get most of the traffic. Recompute them every time?",
        why: "Popular prefixes are served from cache (and browser or CDN caches), so almost nothing hits the index.",
      },
      {
        id: "index",
        kind: "component",
        title: "Prefix index with precomputed top-K",
        types: [...DB, "search"],
        hint: "Where do completions for every prefix live?",
        why: "A trie (or key-value store keyed by prefix) holds the precomputed top 10 per prefix.",
      },
      {
        id: "log",
        kind: "component",
        title: "Log pipeline for popularity",
        types: ASYNC,
        hint: "How do suggestions learn what's trending?",
        why: "Completed searches stream into a pipeline that aggregates counts.",
      },
      {
        id: "agg",
        kind: "connection",
        title: "Aggregators rebuild the index",
        from: ASYNC,
        to: ["worker"],
        hint: "Something needs to turn raw logs into ranked prefixes.",
        why: "Workers aggregate counts per query and periodically rebuild the top-K index offline.",
      },
    ],
    solution: {
      nodes: [
        { id: "c", type: "client", label: "Search Box", col: 0, row: 1, note: "Debounces keystrokes and caches responses per prefix in the browser." },
        { id: "lb", type: "load_balancer", label: "Load Balancer", col: 1, row: 1, note: "Spreads the keystroke flood." },
        { id: "svc", type: "service", label: "Suggest Service", col: 2, row: 1, note: "Looks up the prefix's precomputed top-K. No sorting at request time." },
        { id: "cache", type: "cache", label: "Hot Prefix Cache", col: 3, row: 0, note: "Short prefixes are extremely popular, so hit rates are very high.", config: { hitRate: 0.95 } },
        { id: "idx", type: "nosql_db", label: "Prefix Index (Top-K)", col: 3, row: 1.2, note: "prefix → 10 best completions, sharded by prefix and rebuilt from logs." },
        { id: "log", type: "stream", label: "Query Log", col: 2, row: 2.4, note: "Every completed search is logged here." },
        { id: "agg", type: "worker", label: "Aggregation Jobs", col: 3, row: 2.4, note: "Count queries per window, apply decay for freshness, and rebuild top-K per prefix." },
      ],
      edges: [
        { from: "c", to: "lb" },
        { from: "lb", to: "svc" },
        { from: "svc", to: "cache" },
        { from: "svc", to: "idx", label: "miss" },
        { from: "svc", to: "log", label: "completed searches", ratio: 0.1 },
        { from: "log", to: "agg" },
        { from: "agg", to: "idx", label: "rebuild", ratio: 0.01 },
      ],
    },
    decisions: [
      {
        q: "Why precompute top-K per prefix?",
        a: "Walking a trie and sorting every descendant on each keystroke is too slow at 350k req/s. Storing the answer per prefix makes each read O(1).",
      },
      {
        q: "Why rebuild offline instead of updating live?",
        a: "Live counter updates on every search would add huge write load to a latency-critical path. Batch aggregation (hourly, with a faster trending job) is plenty fresh.",
      },
      {
        q: "Where does caching happen?",
        a: "At every layer: the browser caches per prefix, a CDN or edge cache handles common prefixes, and Redis sits in front of the index.",
      },
    ],
    deepDives: [
      { q: "Personalization?", a: "Blend the global top-K with the user's recent searches client-side or in a light re-ranking step. The global index stays shared." },
      { q: "Filtering bad suggestions?", a: "Apply a blocklist during the offline build, so offensive completions never enter the index." },
      { q: "Sharding the trie?", a: "Shard by prefix range, balanced by traffic rather than alphabet (far more queries start with 's' than 'x')." },
    ],
    mistakes: [
      "Querying a SQL LIKE 'prefix%' on each keystroke.",
      "Sorting candidates at request time.",
      "Updating counts synchronously on every search.",
    ],
  },
  {
    slug: "web-crawler",
    title: "Web Crawler",
    tagline: "Design Google's web crawler",
    difficulty: "Hard",
    category: "Search",
    askedAt: ["Google"],
    concepts: ["URL frontier", "Politeness / per-domain rate limits", "Deduplication (seen set)", "Pipeline of queues", "DNS caching"],
    functional: ["Start from seed URLs and discover new pages by following links", "Store page content for indexing", "Recrawl pages periodically"],
    nonFunctional: ["Billions of pages, crawled continuously", "Polite: never hammer one site", "Robust to traps, timeouts and malformed HTML"],
    estimates: [
      "10B pages per month ≈ 4k pages/sec",
      "Average page 100 KB → ~400 MB/s of downloads, ~1 PB/month raw",
      "Fetches take ~0.5–2 s each, so thousands of concurrent fetches are needed",
    ],
    api: [
      { method: "POST", path: "(internal) frontier.enqueue(url, priority)", purpose: "Add a discovered URL, deduplicated against the seen set" },
      { method: "GET", path: "(internal) frontier.next(domain)", purpose: "A fetcher takes the next URL for a domain whose politeness delay has passed" },
    ],
    dataModel: [
      {
        entity: "URL record",
        store: "Bigtable / Cassandra",
        fields: "url_hash (PK), url, last_crawled, content_hash, status",
        why: "Billions of rows keyed by URL. It answers 'have we seen this?' and 'when did we last crawl it?'.",
      },
      {
        entity: "Raw page",
        store: "S3 / GCS",
        fields: "pages/{url_hash}/{crawl_ts}.html.gz",
        why: "Huge immutable blobs for the indexing pipeline.",
      },
    ],
    checkpoints: [
      {
        id: "frontier",
        kind: "component",
        title: "A URL frontier queue",
        types: ASYNC,
        hint: "Where do millions of URLs wait to be crawled, in priority order?",
        why: "The frontier is a set of queues (per priority, per domain) that feeds fetchers and enforces politeness.",
      },
      {
        id: "fetchers",
        kind: "connection",
        title: "Fetcher workers pull from the frontier",
        from: ASYNC,
        to: ["worker"],
        hint: "What actually downloads pages?",
        why: "A large pool of fetchers pulls URLs, respects robots.txt, and downloads pages concurrently.",
      },
      {
        id: "blob",
        kind: "component",
        title: "Raw pages in object storage",
        types: ["object_storage"],
        hint: "Where does a petabyte a month of HTML go?",
        why: "Store raw pages in object storage for parsing and indexing.",
      },
      {
        id: "store-pages",
        kind: "connection",
        title: "Fetchers write pages to storage",
        from: ["worker"],
        to: ["object_storage"],
        hint: "Wire the fetchers to storage.",
        why: "Each fetched page is written once and handed on by reference.",
      },
      {
        id: "dns",
        kind: "component",
        title: "DNS cache",
        types: ["cache"],
        hint: "Every fetch needs a DNS lookup. At 4k pages/sec, is the system resolver enough?",
        why: "A local DNS cache avoids a slow, rate-limited lookup on every fetch.",
      },
      {
        id: "seen",
        kind: "component",
        title: "Seen-URL store",
        types: DB,
        hint: "The same URL appears on millions of pages. How do you avoid crawling it a million times?",
        why: "A URL store (often fronted by a Bloom filter) dedupes URLs and tracks recrawl times.",
      },
    ],
    solution: {
      nodes: [
        { id: "seeds", type: "client", label: "Seeds & Recrawl Feed", col: 0, row: 1, note: "Seed URLs plus pages due for recrawl. The traffic slider sets how fast URLs enter." },
        { id: "frontier", type: "queue", label: "URL Frontier", col: 1, row: 1, note: "Priority queues, then per-domain queues with delays, so no site is hammered." },
        { id: "fetch", type: "worker", label: "Fetchers", col: 2, row: 1, note: "Thousands of concurrent downloads. Honor robots.txt, time out slow hosts.", config: { replicas: 20, capacity: 100, latencyMs: 400 } },
        { id: "dns", type: "cache", label: "DNS Cache", col: 2, row: 0, note: "Resolved hostnames cached locally." },
        { id: "raw", type: "object_storage", label: "Raw Pages", col: 3, row: 0, note: "Compressed HTML, keyed by URL hash and crawl time." },
        { id: "pq", type: "queue", label: "Parse Queue", col: 3, row: 1, note: "References to fetched pages awaiting parsing." },
        { id: "parse", type: "worker", label: "Parsers", col: 4, row: 1, note: "Extract links and text, dedupe content by hash, and push new URLs back to the frontier.", config: { replicas: 6 } },
        { id: "seen", type: "nosql_db", label: "URL Store (Seen Set)", col: 5, row: 0.5, note: "Has this URL been seen? When was it last crawled?" },
        { id: "index", type: "search", label: "Search Index", col: 5, row: 1.5, note: "Parsed content, handed off to indexing." },
      ],
      edges: [
        { from: "seeds", to: "frontier" },
        { from: "frontier", to: "fetch" },
        { from: "fetch", to: "dns", label: "resolve" },
        { from: "fetch", to: "raw", label: "store page" },
        { from: "fetch", to: "pq" },
        { from: "pq", to: "parse" },
        { from: "parse", to: "seen", label: "dedupe links" },
        { from: "parse", to: "index" },
      ],
    },
    decisions: [
      {
        q: "How does the crawler stay polite?",
        a: "The frontier keeps a queue per domain (or per host) with a minimum delay between fetches, and each fetcher takes a URL only when its domain is ready. robots.txt is cached and honored.",
      },
      {
        q: "Why a pipeline of queues?",
        a: "Fetching is slow and network-bound, while parsing is CPU-bound. Queues between the stages let each scale independently and absorb uneven speeds.",
      },
      {
        q: "How do you avoid re-crawling duplicates?",
        a: "Normalize URLs and check a Bloom filter (fast, with occasional false positives) backed by the URL store. Also hash page content, since different URLs often serve identical pages.",
      },
    ],
    deepDives: [
      { q: "Crawler traps?", a: "Infinite calendars and session IDs in URLs. Cap depth per site, strip tracking parameters, and limit the pages crawled per domain." },
      { q: "Recrawl frequency?", a: "Score pages by change rate and importance. News pages get recrawled hourly, static pages monthly." },
      { q: "Distribution?", a: "Partition the frontier by domain hash across crawler nodes, so each domain's politeness is enforced in one place." },
    ],
    mistakes: [
      "One global FIFO queue, which ends up hammering a single site with parallel requests.",
      "No deduplication, so the crawler loops forever.",
      "Fetching and parsing in the same step, so slow network I/O starves the CPU work.",
    ],
  },
  {
    slug: "proximity-service",
    title: "Proximity Service",
    tagline: "Design Yelp / nearby places",
    difficulty: "Easy",
    category: "Location",
    askedAt: [],
    concepts: ["Geohash / quadtree", "Read-heavy geo search", "Separate read and write paths", "Index updates"],
    functional: ["Find businesses near a location within a radius", "View business details and reviews", "Owners add and update businesses"],
    nonFunctional: ["Search in < 200 ms", "Reads vastly outnumber writes", "New businesses can take minutes to appear"],
    estimates: [
      "100M DAU × 5 searches ≈ 6k searches/sec",
      "200M businesses × ~1 KB ≈ 200 GB — the geo index fits in memory on a few nodes",
      "Business updates are rare: ~100/sec",
    ],
    api: [
      { method: "GET", path: "/search?lat=&lng=&radius=&q=", purpose: "Nearby businesses, ranked by distance and rating" },
      { method: "GET", path: "/businesses/{id}", purpose: "Business details" },
      { method: "POST", path: "/businesses", purpose: "Owner creates or updates a listing" },
    ],
    dataModel: [
      {
        entity: "Business",
        store: "PostgreSQL",
        fields: "id, name, category, lat, lng, geohash, rating",
        why: "The source of truth, with relational queries for owners and reviews.",
      },
      {
        entity: "Geo index",
        store: "Elasticsearch geo / Redis GEO",
        fields: "geohash prefix → business IDs",
        why: "Nearby search becomes a lookup of a few neighboring cells.",
      },
    ],
    checkpoints: [
      {
        id: "entry",
        kind: "connection",
        title: "Clients enter via a load balancer",
        from: ["client"],
        to: ENTRY,
        hint: "Front door.",
        why: "Standard entry for stateless search servers.",
      },
      {
        id: "geo",
        kind: "component",
        title: "Geospatial index",
        types: ["search", "cache"],
        hint: "'Everything within 2 km' — scanning 200M rows by distance on every request won't work.",
        why: "Geohash or quadtree cells turn radius search into looking up a handful of nearby cells.",
      },
      {
        id: "search-conn",
        kind: "connection",
        title: "Search service queries the geo index",
        from: ["service"],
        to: ["search", "cache"],
        hint: "Wire search to the index.",
        why: "The search service looks up the query cell plus its neighbors, then filters and ranks.",
      },
      {
        id: "split",
        kind: "component",
        title: "Separate search and business services",
        types: ["service"],
        min: 2,
        hint: "Searches and edits have very different loads.",
        why: "A read-heavy search service scales separately from the business CRUD service.",
      },
      {
        id: "db",
        kind: "component",
        title: "Business database",
        types: DB,
        hint: "Where's the source of truth for listings?",
        why: "A relational database holds listings, and the geo index is derived from it.",
      },
    ],
    solution: {
      nodes: [
        { id: "c", type: "client", label: "Users", col: 0, row: 1, note: "Search nearby far more often than they edit anything." },
        { id: "lb", type: "load_balancer", label: "Load Balancer", col: 1, row: 1, note: "Sends searches and edits to their own services." },
        { id: "search", type: "service", label: "Nearby Search", col: 2, row: 0.4, note: "Computes the user's geohash cell plus 8 neighbors, then filters and ranks the results." },
        { id: "hot", type: "cache", label: "Hot Area Cache", col: 3, row: -0.4, note: "Popular city-center cells are cached." },
        { id: "geo", type: "search", label: "Geo Index", col: 3, row: 0.8, note: "Elasticsearch geo_distance queries, or a geohash → IDs map." },
        { id: "biz", type: "service", label: "Business Service", col: 2, row: 1.9, note: "Creates and updates listings, and emits changes for the index." },
        { id: "db", type: "sql_db", label: "Businesses", col: 3, row: 1.9, note: "Source of truth for listings." },
        { id: "q", type: "queue", label: "Index Updates", col: 4, row: 1.9, note: "Changes flow to the index asynchronously." },
        { id: "ix", type: "worker", label: "Indexer", col: 5, row: 1.2, note: "Writes updated listings into the geo index." },
      ],
      edges: [
        { from: "c", to: "lb" },
        { from: "lb", to: "search", ratio: 4 },
        { from: "lb", to: "biz", ratio: 1 },
        { from: "search", to: "hot" },
        { from: "search", to: "geo", label: "cells", ratio: 0.2 },
        { from: "biz", to: "db" },
        { from: "biz", to: "q", label: "changes", ratio: 0.05 },
        { from: "q", to: "ix" },
        { from: "ix", to: "geo" },
      ],
    },
    decisions: [
      {
        q: "Geohash or quadtree?",
        a: "Geohash is a simple string prefix: easy to store, shard and cache. A quadtree adapts to density (dense cities get smaller cells) but is an in-memory structure you must rebuild. Both work; geohash is easier to explain and operate.",
      },
      {
        q: "Why search neighboring cells?",
        a: "A point near a cell edge has close neighbors in the adjacent cell. Querying the cell plus its 8 neighbors avoids missing them.",
      },
      {
        q: "Why update the index asynchronously?",
        a: "Edits are rare and a few minutes of lag is fine. Async indexing keeps writes fast and the index read-optimized.",
      },
    ],
    deepDives: [
      { q: "Choosing the geohash precision?", a: "Pick the precision whose cell size matches the radius (e.g. 6 characters ≈ 1.2 km). Widen to neighbors or a shorter prefix if too few results come back." },
      { q: "Ranking?", a: "Score by distance, rating and relevance to the query text. Elasticsearch can combine all three." },
      { q: "Scaling reads?", a: "The index is small, so replicate it widely. Cache popular areas, and CDN-cache the business detail pages." },
    ],
    mistakes: [
      "Computing distance to every business in SQL per request.",
      "Forgetting neighboring cells at cell boundaries.",
      "Writing to the index synchronously on every edit.",
    ],
  },
  {
    slug: "ticketmaster",
    title: "Ticket Booking",
    tagline: "Design Ticketmaster",
    difficulty: "Medium",
    category: "Commerce",
    askedAt: [],
    concepts: ["Seat holds with TTL locks", "Strong consistency / transactions", "Virtual waiting room", "Flash traffic", "Idempotent checkout"],
    functional: ["Browse events and view seat maps", "Hold seats while checking out", "Book seats — each seat sold at most once", "Search events"],
    nonFunctional: ["Never double-sell a seat", "Survive huge on-sale spikes (a stadium in minutes)", "Browsing can be eventually consistent"],
    estimates: [
      "Popular on-sale: 10M users for 50k seats, mostly in the first minutes",
      "Browsing is ~100× booking traffic",
      "A seat hold lasts ~10 minutes while the user pays",
    ],
    api: [
      { method: "GET", path: "/events/{id}", purpose: "Event details plus seat map availability (cached)" },
      { method: "POST", path: "/holds", purpose: "Body { eventId, seatIds } → holdId, expiring in 10 minutes" },
      { method: "POST", path: "/bookings", purpose: "Body { holdId, paymentToken, idempotencyKey } → confirmed booking" },
    ],
    dataModel: [
      {
        entity: "Seat hold",
        store: "Redis",
        fields: "hold:{event}:{seat} → user_id (SET NX, EX 600)",
        why: "An atomic set-if-absent with expiry is a lock that frees itself if the user walks away.",
      },
      {
        entity: "Booking / seat",
        store: "PostgreSQL",
        fields: "seat(event_id, seat_id, status, booking_id), booking(id, user_id, total, state)",
        why: "The final sale must be ACID: a transaction marks seats sold only if they're still available.",
      },
    ],
    checkpoints: [
      {
        id: "entry",
        kind: "connection",
        title: "Clients enter via a load balancer",
        from: ["client"],
        to: ENTRY,
        hint: "Front door.",
        why: "Standard entry point.",
      },
      {
        id: "admission",
        kind: "component",
        title: "Waiting room or admission control",
        types: ["rate_limiter", "queue"],
        hint: "10M people arrive for 50k seats at once. Let them all hit the booking service?",
        why: "A virtual waiting room admits users at a rate the booking path can handle, and everyone else waits in line.",
      },
      {
        id: "locks",
        kind: "component",
        title: "Seat holds with expiry",
        types: ["cache"],
        hint: "Two people click the same seat at the same moment. Who gets it, and for how long?",
        why: "An atomic SET NX with a 10-minute TTL reserves a seat for one user and releases it if they abandon checkout.",
      },
      {
        id: "sql",
        kind: "component",
        title: "Transactional database for sales",
        types: ["sql_db"],
        hint: "Selling a seat twice is unacceptable. What kind of store gives you that guarantee?",
        why: "A relational transaction confirms seats only if they're still unsold.",
      },
      {
        id: "split",
        kind: "component",
        title: "Separate browsing and booking services",
        types: ["service"],
        min: 2,
        hint: "Browsing is huge and cacheable; booking is small and must be correct.",
        why: "Separate services scale and protect the critical booking path.",
      },
      {
        id: "cdn",
        kind: "component",
        title: "CDN for event pages",
        types: ["cdn"],
        hint: "Millions of people refreshing the same event page.",
        why: "Static event pages and images come from the CDN.",
      },
    ],
    solution: {
      nodes: [
        { id: "c", type: "client", label: "Fans", col: 0, row: 1.5, note: "Mostly browsing and refreshing; a few actually checking out." },
        { id: "cdn", type: "cdn", label: "CDN", col: 1, row: 0, note: "Event pages, images and seat-map assets." },
        { id: "lb", type: "load_balancer", label: "Load Balancer", col: 1, row: 1.5, note: "Front door for API calls." },
        { id: "wr", type: "rate_limiter", label: "Virtual Waiting Room", col: 2, row: 1.5, note: "Admits users at a safe rate during on-sales. Everyone else waits with a queue position." },
        { id: "ev", type: "service", label: "Event Service", col: 3, row: 0.8, note: "Event details and seat availability, served from cache." },
        { id: "evc", type: "cache", label: "Event Cache", col: 4, row: 0.3, note: "Event pages and approximate availability." },
        { id: "bk", type: "service", label: "Booking Service", col: 3, row: 2.3, note: "Takes seat holds, then confirms bookings in one transaction after payment." },
        { id: "holds", type: "cache", label: "Seat Holds (TTL locks)", col: 4, row: 2.3, note: "SET NX EX 600 per seat. Expires automatically if checkout is abandoned." },
        { id: "db", type: "sql_db", label: "Bookings DB", col: 5, row: 1.5, note: "Seats and bookings. The transaction is the final guard against double-selling.", config: { replicas: 2 } },
        { id: "q", type: "queue", label: "Confirmations", col: 4, row: 3.3, note: "Tickets and emails, sent asynchronously." },
        { id: "mail", type: "worker", label: "Ticket Issuer", col: 5, row: 3.3, note: "Generates tickets and sends confirmations." },
      ],
      edges: [
        { from: "c", to: "cdn", label: "static" },
        { from: "c", to: "lb" },
        { from: "lb", to: "wr" },
        { from: "wr", to: "ev", ratio: 9 },
        { from: "wr", to: "bk", ratio: 1 },
        { from: "ev", to: "evc" },
        { from: "ev", to: "db", label: "miss" },
        { from: "bk", to: "holds", label: "hold seats" },
        { from: "bk", to: "db", label: "confirm", ratio: 1 },
        { from: "bk", to: "q", ratio: 0.1 },
        { from: "q", to: "mail" },
      ],
    },
    decisions: [
      {
        q: "Why Redis holds and a SQL transaction?",
        a: "Holds give fast, self-expiring reservations during checkout without locking database rows for minutes. The final transaction (UPDATE seats … WHERE status = 'available') is the real guarantee, even if a hold misbehaves.",
      },
      {
        q: "Why a waiting room?",
        a: "Without admission control, an on-sale is a thundering herd that takes everything down. Admitting a steady stream keeps the booking path healthy and is fairer to fans.",
      },
      {
        q: "How do you make checkout safe to retry?",
        a: "Idempotency keys on booking and payment: a retried request returns the original result instead of charging twice.",
      },
    ],
    deepDives: [
      { q: "Showing live seat availability?", a: "Push availability updates over SSE or WebSocket for the event, and tolerate slight staleness, since the hold step is authoritative." },
      { q: "Search?", a: "Index events in Elasticsearch, updated asynchronously from the events database." },
      { q: "Bots?", a: "CAPTCHAs, per-account limits and verified-fan presales, enforced at the waiting room." },
    ],
    mistakes: [
      "Locking seat rows in the database for the whole checkout.",
      "No admission control for on-sales.",
      "Relying on the cache alone (holds) without a transactional final check.",
    ],
  },
  {
    slug: "payment-system",
    title: "Payment System",
    tagline: "Design Stripe / a payment service",
    difficulty: "Hard",
    category: "Commerce",
    askedAt: [],
    concepts: ["Idempotency keys", "Double-entry ledger", "Exactly-once effects via at-least-once + dedup", "Reconciliation", "Async provider calls"],
    functional: ["Merchants charge customers", "Refunds", "Merchants get webhooks when a payment's status changes", "Accurate balances and payouts"],
    nonFunctional: ["Never charge twice, never lose a payment", "Strong consistency for money", "Auditable history", "High availability for accepting payments"],
    estimates: [
      "1B payments/year ≈ 30/sec average, 10× peaks",
      "Each payment → several ledger entries",
      "Card network calls take 1–3 s and can time out ambiguously",
    ],
    api: [
      { method: "POST", path: "/payments", purpose: "Body { amount, currency, source, idempotencyKey } → payment in 'processing'" },
      { method: "POST", path: "/payments/{id}/refunds", purpose: "Refund all or part of a payment" },
      { method: "GET", path: "/payments/{id}", purpose: "Current status" },
    ],
    dataModel: [
      {
        entity: "Ledger entry",
        store: "PostgreSQL",
        fields: "entry_id, payment_id, account, debit, credit, created_at (append-only)",
        why: "Double-entry bookkeeping in ACID transactions: every movement balances, and the history is immutable.",
      },
      {
        entity: "Idempotency key",
        store: "Redis + DB",
        fields: "merchant_id:key → payment_id, response (24h TTL)",
        why: "A retried request returns the stored response instead of creating a second charge.",
      },
    ],
    checkpoints: [
      {
        id: "entry",
        kind: "connection",
        title: "Merchants call a gateway",
        from: ["client"],
        to: ENTRY,
        hint: "Who authenticates merchants and throttles abuse?",
        why: "An API gateway handles auth, TLS and rate limits.",
      },
      {
        id: "idem",
        kind: "component",
        title: "Idempotency key store",
        types: ["cache", ...DB],
        hint: "The merchant's request timed out, so they retry. How do you not charge the card twice?",
        why: "Store each idempotency key with its result. Retries get the same answer, never a second charge.",
      },
      {
        id: "ledger",
        kind: "component",
        title: "Transactional double-entry ledger",
        types: ["sql_db"],
        hint: "Money needs a guarantee that every debit has a matching credit. Which store gives you transactions?",
        why: "An append-only double-entry ledger in a relational database, written transactionally.",
      },
      {
        id: "async",
        kind: "component",
        title: "Async processing of provider calls",
        types: ASYNC,
        hint: "Card networks take seconds and sometimes time out. Hold the API request open?",
        why: "Record the intent, return 'processing', and let workers call the card network and handle retries.",
      },
      {
        id: "exec",
        kind: "connection",
        title: "Workers execute payments",
        from: ASYNC,
        to: ["worker"],
        hint: "Who talks to the payment processor?",
        why: "Executor workers call the processor, record the outcome in the ledger, and emit webhooks.",
      },
    ],
    solution: {
      nodes: [
        { id: "c", type: "client", label: "Merchants", col: 0, row: 1, note: "Call the API with an idempotency key on every request." },
        { id: "gw", type: "api_gateway", label: "API Gateway", col: 1, row: 1, note: "Auth, TLS and per-merchant rate limits." },
        { id: "pay", type: "service", label: "Payment Service", col: 2, row: 1, note: "Checks the idempotency key, records the intent in the ledger, and emits a payment event." },
        { id: "idem", type: "cache", label: "Idempotency Keys", col: 3, row: 0, note: "merchant:key → stored response, with a TTL." },
        { id: "ledger", type: "sql_db", label: "Ledger (Double-Entry)", col: 3, row: 1, note: "Append-only entries in ACID transactions. Balances are derived, never overwritten.", config: { replicas: 2 } },
        { id: "events", type: "stream", label: "Payment Events", col: 3, row: 2, note: "Durable log of state changes." },
        { id: "exec", type: "worker", label: "Processor Executor", col: 4, row: 1.6, note: "Calls card networks, retries safely, and writes outcomes to the ledger.", config: { replicas: 4, capacity: 300 } },
        { id: "hooks", type: "worker", label: "Webhook Sender", col: 4, row: 2.6, note: "Notifies merchants with signed, retried webhooks.", config: { replicas: 4, capacity: 300 } },
        { id: "recon", type: "scheduler", label: "Nightly Reconciliation", col: 5, row: 0.6, note: "Compares the ledger with processor settlement files to catch any drift." },
      ],
      edges: [
        { from: "c", to: "gw" },
        { from: "gw", to: "pay" },
        { from: "pay", to: "idem", label: "dedupe" },
        { from: "pay", to: "ledger", label: "record intent", ratio: 1 },
        { from: "pay", to: "events" },
        { from: "events", to: "exec" },
        { from: "events", to: "hooks" },
        { from: "exec", to: "ledger", label: "outcome" },
        { from: "recon", to: "ledger" },
      ],
    },
    decisions: [
      {
        q: "Why a double-entry ledger?",
        a: "Every movement is a pair of debits and credits that must sum to zero, so errors show up as imbalances. Append-only entries give a full audit trail, and you never UPDATE a balance in place.",
      },
      {
        q: "How do you get 'exactly once' with unreliable networks?",
        a: "You can't guarantee exactly-once delivery. You get exactly-once effects with at-least-once delivery plus idempotency: the same key yields the same result, and processor calls carry their own idempotency keys.",
      },
      {
        q: "What if the card network times out?",
        a: "The outcome is unknown, so mark the payment 'pending' and query the processor or retry with the same idempotency key. Nightly reconciliation catches anything still ambiguous.",
      },
    ],
    deepDives: [
      { q: "Consistency across services?", a: "Use the outbox pattern: write the ledger entry and an outbox row in one transaction, and a relay publishes the event. That avoids dual-write inconsistency." },
      { q: "Payouts?", a: "A scheduled job sums each merchant's settled balance from the ledger and initiates bank transfers, which are themselves ledger entries." },
      { q: "Fraud?", a: "Score risk synchronously (fast model) before authorizing, and do deeper async review that can flag or refund." },
    ],
    mistakes: [
      "No idempotency, so client retries double-charge.",
      "Storing a mutable balance column updated in place.",
      "Calling the card network synchronously and failing the request on timeout.",
    ],
  },
  {
    slug: "google-docs",
    title: "Collaborative Editor",
    tagline: "Design Google Docs",
    difficulty: "Hard",
    category: "Collaboration",
    askedAt: ["Google"],
    concepts: ["Operational transform / CRDTs", "WebSockets", "Per-document ordering", "Operation log + snapshots", "Presence & cursors"],
    functional: ["Several people edit a document at the same time", "Everyone sees others' edits and cursors live", "Full version history", "Share with permissions"],
    nonFunctional: ["Edits appear for others within ~100 ms", "All replicas converge to the same text", "Never lose an edit"],
    estimates: [
      "Most docs have 1–5 active editors, a few have hundreds",
      "~10 operations/sec per active editor",
      "Operation logs grow forever, so snapshot every N operations",
    ],
    api: [
      { method: "WS", path: "/docs/{id}/edit", purpose: "Send operations and receive transformed operations, cursors and presence" },
      { method: "GET", path: "/docs/{id}", purpose: "Latest snapshot plus operations since it" },
      { method: "GET", path: "/docs/{id}/history", purpose: "Version history from snapshots and the operation log" },
    ],
    dataModel: [
      {
        entity: "Operation",
        store: "Cassandra / Bigtable",
        fields: "doc_id (partition), revision (clustering), op, author, ts",
        why: "An append-only, ordered log per document, read in order to rebuild state.",
      },
      {
        entity: "Snapshot",
        store: "S3",
        fields: "docs/{id}/rev-{n}",
        why: "Loading a doc means the latest snapshot plus a short tail of operations, not a replay from the beginning.",
      },
      {
        entity: "Doc metadata / ACL",
        store: "PostgreSQL",
        fields: "doc_id, owner, title, permissions",
        why: "Relational sharing and permission queries.",
      },
    ],
    checkpoints: [
      {
        id: "ws",
        kind: "component",
        title: "WebSocket collaboration servers",
        types: ["websocket"],
        hint: "Edits and cursors must stream both ways with ~100 ms latency.",
        why: "Editors hold WebSockets to a collaboration server, which is the single place ordering that document's operations.",
      },
      {
        id: "log",
        kind: "component",
        title: "Ordered operation log",
        types: ASYNC,
        hint: "How do you keep every edit, in order, for history and recovery?",
        why: "Every accepted operation is appended to a per-document ordered log.",
      },
      {
        id: "ws-log",
        kind: "connection",
        title: "Accepted operations go to the log",
        from: ["websocket"],
        to: ASYNC,
        hint: "Connect the collaboration server to the log.",
        why: "The server transforms each operation against concurrent ones, assigns a revision, and appends it before broadcasting.",
      },
      {
        id: "store",
        kind: "component",
        title: "Durable operation / snapshot store",
        types: [...DB, "object_storage"],
        hint: "Where does history live long-term?",
        why: "Operations persist in a wide-column store, and periodic snapshots go to object storage.",
      },
      {
        id: "state",
        kind: "component",
        title: "Fast session state",
        types: ["cache"],
        hint: "Which server owns this document right now, and who's in it?",
        why: "Redis tracks doc → server assignment, presence and cursors.",
      },
    ],
    solution: {
      nodes: [
        { id: "c", type: "client", label: "Editors", col: 0, row: 1, note: "Apply their own edits locally at once, then send operations to the server." },
        { id: "lb", type: "load_balancer", label: "Load Balancer", col: 1, row: 1, note: "Routes each document's editors to the server that owns it (sticky by doc ID)." },
        { id: "ws", type: "websocket", label: "Collaboration Servers", col: 2, row: 0.6, note: "Order operations per document, transform concurrent edits (OT), and broadcast to editors." },
        { id: "state", type: "cache", label: "Session State", col: 3, row: -0.3, note: "Doc-to-server ownership, presence and cursors." },
        { id: "log", type: "stream", label: "Operation Log", col: 3, row: 0.8, note: "Accepted operations, in revision order." },
        { id: "snap", type: "worker", label: "Persister & Snapshotter", col: 4, row: 0.8, note: "Writes operations durably and snapshots every N revisions.", config: { replicas: 6 } },
        { id: "ops", type: "nosql_db", label: "Operations Store", col: 5, row: 0.3, note: "Full per-document history." },
        { id: "snaps", type: "object_storage", label: "Snapshots", col: 5, row: 1.3, note: "Periodic full-document snapshots for fast loads." },
        { id: "docs", type: "service", label: "Document Service", col: 2, row: 2.1, note: "Opens docs (snapshot plus tail), history, sharing." },
        { id: "meta", type: "sql_db", label: "Docs & Permissions", col: 3, row: 2.1, note: "Titles, owners, ACLs." },
      ],
      edges: [
        { from: "c", to: "lb" },
        { from: "lb", to: "ws", ratio: 4 },
        { from: "lb", to: "docs", ratio: 1 },
        { from: "ws", to: "state" },
        { from: "ws", to: "log", label: "append" },
        { from: "log", to: "snap" },
        { from: "snap", to: "ops" },
        { from: "snap", to: "snaps", label: "every N ops", ratio: 0.01 },
        { from: "docs", to: "meta" },
      ],
    },
    decisions: [
      {
        q: "OT or CRDT?",
        a: "Operational Transform (Google Docs) needs a central server to order and transform operations. It's simpler to reason about with one authority per document. CRDTs converge without a coordinator, which is great for offline and peer-to-peer use, at the cost of heavier metadata.",
      },
      {
        q: "Why route all editors of a doc to one server?",
        a: "OT needs a single ordering point per document. Sticky routing by doc ID keeps that simple, and a server failure hands the doc to another server that recovers from the log.",
      },
      {
        q: "Why snapshots?",
        a: "Replaying millions of operations to open a document is slow. A snapshot every N operations bounds the replay to a short tail.",
      },
    ],
    deepDives: [
      { q: "Cursors and presence?", a: "Ephemeral: broadcast them through the collaboration server and keep them in Redis. They're never stored in the operation log." },
      { q: "Offline edits?", a: "Queue operations locally and rebase them onto the server's revisions when reconnecting. That's where CRDTs shine." },
      { q: "Huge documents?", a: "Split into sections or blocks with independent operation streams, so hundreds of editors don't all contend on one ordering point." },
    ],
    mistakes: [
      "Last-write-wins on the whole document, so concurrent edits are lost.",
      "Spreading one document's editors across servers without a single ordering point.",
      "Replaying the entire history to open a document.",
    ],
  },
];
