import { ASYNC, DB, ENTRY, type Problem } from "./types";

export const STORAGE_SOCIAL: Problem[] = [
  {
    slug: "pastebin",
    title: "Pastebin",
    tagline: "Design Pastebin / GitHub Gist",
    difficulty: "Easy",
    category: "Storage",
    askedAt: [],
    concepts: ["Blob vs metadata storage", "Read-heavy caching", "Expiry / TTL", "Unique IDs"],
    functional: ["Upload a block of text and get a short link", "Anyone with the link can read the paste", "Pastes can expire", "Optional syntax highlighting"],
    nonFunctional: ["Reads outnumber writes about 10:1", "Pastes up to 10 MB", "Highly durable — a paste must never be lost"],
    estimates: [
      "1M new pastes/day ≈ 12 writes/sec, ~120 reads/sec (peaks 10× higher)",
      "Average paste 10 KB × 1M/day ≈ 10 GB/day ≈ 3.6 TB/year",
      "Metadata is ~200 bytes per paste — tiny next to the content",
    ],
    api: [
      { method: "POST", path: "/pastes", purpose: "Body { content, language?, expiresIn? } → { id, url }" },
      { method: "GET", path: "/pastes/{id}", purpose: "Returns content and metadata (404 once expired)" },
      { method: "DELETE", path: "/pastes/{id}", purpose: "Owner deletes a paste" },
    ],
    dataModel: [
      {
        entity: "Paste metadata",
        store: "DynamoDB / Cassandra",
        fields: "id (PK), owner_id, language, size, content_key, created_at, expires_at",
        why: "Small rows, looked up by ID, with native TTL support for expiry.",
      },
      {
        entity: "Paste content",
        store: "S3",
        fields: "pastes/{id} → raw text",
        why: "Up to 10 MB each and terabytes in total. Object storage is far cheaper than database storage for blobs.",
      },
    ],
    checkpoints: [
      {
        id: "entry",
        kind: "connection",
        title: "Traffic enters through a load balancer",
        from: ["client"],
        to: ENTRY,
        hint: "Where do requests land before your servers?",
        why: "A load balancer spreads requests over stateless paste servers and hides failures.",
      },
      {
        id: "blob",
        kind: "component",
        title: "Paste bodies in object storage",
        types: ["object_storage"],
        hint: "Should 10 MB text blobs live in the same database as small metadata rows?",
        why: "Separating big blobs (object storage) from small metadata (database) keeps the database small and fast, and storage cheap.",
      },
      {
        id: "meta",
        kind: "component",
        title: "Metadata store",
        types: DB,
        hint: "Where do you keep who owns a paste and when it expires?",
        why: "A key-value store keyed by paste ID holds metadata, and its TTL feature can handle expiry.",
      },
      {
        id: "cache",
        kind: "component",
        title: "Cache for popular pastes",
        types: ["cache"],
        hint: "A paste shared on social media gets hammered. How do you avoid fetching it from storage every time?",
        why: "Caching hot pastes in Redis (or a CDN) serves viral links from memory.",
      },
      {
        id: "svc-blob",
        kind: "connection",
        title: "Service reads and writes blobs",
        from: ["service"],
        to: ["object_storage"],
        hint: "Connect the service to where paste content lives.",
        why: "Writes upload the content, and reads fetch it on a cache miss.",
      },
    ],
    solution: {
      nodes: [
        { id: "c", type: "client", label: "Users", col: 0, row: 1, note: "Create pastes and open shared links. Reads dominate." },
        { id: "lb", type: "load_balancer", label: "Load Balancer", col: 1, row: 1, note: "Spreads traffic over the paste servers." },
        { id: "svc", type: "service", label: "Paste Service", col: 2, row: 1, note: "Generates the ID, writes metadata and content, and serves reads through the cache." },
        { id: "cache", type: "cache", label: "Hot Paste Cache", col: 3, row: 0, note: "Popular pastes stay in memory, so a viral link doesn't hit storage." },
        { id: "db", type: "nosql_db", label: "Paste Metadata", col: 3, row: 1, note: "Key-value rows keyed by paste ID, with a TTL for expiry." },
        { id: "s3", type: "object_storage", label: "Paste Content", col: 3, row: 2, note: "The raw text, one object per paste. Cheap and extremely durable." },
        { id: "cron", type: "scheduler", label: "Expiry Cleanup", col: 4, row: 1.5, note: "Deletes content objects whose metadata has expired." },
      ],
      edges: [
        { from: "c", to: "lb" },
        { from: "lb", to: "svc" },
        { from: "svc", to: "cache", label: "read-through" },
        { from: "svc", to: "db", label: "metadata" },
        { from: "svc", to: "s3", label: "content (on miss)", ratio: 0.2 },
        { from: "cron", to: "s3", label: "purge expired" },
      ],
    },
    decisions: [
      {
        q: "Why split metadata from content?",
        a: "Metadata is small and queried constantly; content is big and read whole. Keeping blobs in object storage keeps the database lean and cuts storage cost by an order of magnitude.",
      },
      {
        q: "How are IDs generated?",
        a: "The same way as a URL shortener: a random or pre-allocated 7–8 character base62 key. It's unique, short, and not guessable.",
      },
      {
        q: "How does expiry work?",
        a: "Metadata carries expires_at with a database TTL, reads treat expired pastes as missing, and a background job deletes the orphaned content objects.",
      },
    ],
    deepDives: [
      { q: "Would a CDN help?", a: "Yes, for public pastes. Put a CDN in front of GET /pastes/{id} with cache headers, so viral pastes never reach your servers." },
      { q: "How do you handle 10 MB uploads?", a: "Issue a presigned upload URL so clients send content straight to object storage, keeping big payloads off the app servers." },
      { q: "Private pastes?", a: "Store a visibility flag and owner in the metadata, and check auth on read. Private pastes skip the public CDN." },
    ],
    mistakes: [
      "Storing large paste bodies directly in the database.",
      "Scanning the whole table to find expired pastes instead of using TTLs or an expiry index.",
      "Forgetting that reads dominate, and not caching.",
    ],
  },
  {
    slug: "dropbox",
    title: "File Storage & Sync",
    tagline: "Design Dropbox / Google Drive",
    difficulty: "Medium",
    category: "Storage",
    askedAt: ["Google", "Amazon"],
    concepts: ["Chunking & deduplication", "Presigned uploads", "Metadata vs blob storage", "Change notification / sync", "Conflict resolution"],
    functional: ["Upload and download files from any device", "Changes sync automatically to the user's other devices", "Share files and folders", "Keep a version history"],
    nonFunctional: ["Files up to 50 GB", "Never lose data", "Sync within seconds", "Resumable uploads on flaky networks"],
    estimates: [
      "100M users × 10 GB average ≈ 1 EB of storage",
      "50M DAU, ~5 file changes/day each ≈ 3k metadata writes/sec",
      "Chunked 4 MB transfers: most bandwidth goes direct to blob storage, not app servers",
    ],
    api: [
      { method: "POST", path: "/files/upload-session", purpose: "Returns presigned URLs for each 4 MB chunk (only chunks the server doesn't already have)" },
      { method: "POST", path: "/files/commit", purpose: "Body { path, chunkHashes } — records the new version in metadata" },
      { method: "GET", path: "/changes?cursor=", purpose: "Long-poll or WebSocket feed of changes since the device's cursor" },
      { method: "GET", path: "/files/{id}/download", purpose: "Presigned download URLs for the file's chunks" },
    ],
    dataModel: [
      {
        entity: "File / version",
        store: "PostgreSQL (sharded by user)",
        fields: "file_id, owner_id, path, version, chunk_hashes[], updated_at",
        why: "Folder trees, sharing and versions are relational, and commits must be atomic.",
      },
      {
        entity: "Chunk",
        store: "S3",
        fields: "chunks/{sha256} → 4 MB block",
        why: "Content-addressed by hash, so identical chunks across files and users are stored once.",
      },
      {
        entity: "Change log",
        store: "Kafka / queue",
        fields: "user_id, file_id, version, seq",
        why: "An ordered stream of changes that sync servers push to connected devices.",
      },
    ],
    checkpoints: [
      {
        id: "entry",
        kind: "connection",
        title: "Clients reach the API through a load balancer",
        from: ["client"],
        to: ENTRY,
        hint: "Where do metadata requests go?",
        why: "The API servers are stateless behind a load balancer. Only small metadata passes through them.",
      },
      {
        id: "blob",
        kind: "component",
        title: "Chunks in object storage",
        types: ["object_storage"],
        hint: "Where do exabytes of file content live?",
        why: "Object storage holds the chunks. It's cheap, durable, and unlimited.",
      },
      {
        id: "direct",
        kind: "connection",
        title: "Clients transfer chunks directly to storage",
        from: ["client"],
        to: ["object_storage"],
        hint: "Should a 50 GB upload stream through your API servers?",
        why: "Presigned URLs let devices upload and download chunks straight from object storage, so your servers only handle metadata.",
      },
      {
        id: "meta",
        kind: "component",
        title: "Metadata database",
        types: DB,
        hint: "Where do file paths, versions and sharing live?",
        why: "A relational database holds the file tree and versions, with atomic commits.",
      },
      {
        id: "changes",
        kind: "component",
        title: "Change log for sync",
        types: ASYNC,
        hint: "How do your other devices find out a file changed?",
        why: "Every commit emits a change event, and sync servers consume the log to notify devices.",
      },
      {
        id: "push",
        kind: "component",
        title: "Push channel to devices",
        types: ["websocket"],
        hint: "Should every device poll every few seconds?",
        why: "Devices hold a WebSocket (or long-poll) connection, and the sync service pushes 'fetch changes since cursor X'.",
      },
    ],
    solution: {
      nodes: [
        { id: "c", type: "client", label: "Desktop & Mobile Clients", col: 0, row: 1.5, note: "Split files into 4 MB chunks, hash them, and only upload the chunks the server doesn't already have." },
        { id: "lb", type: "load_balancer", label: "Load Balancer", col: 1, row: 1, note: "Fronts the metadata API. File bytes never pass through it." },
        { id: "meta", type: "service", label: "Metadata Service", col: 2, row: 1, note: "Issues presigned chunk URLs, commits new versions atomically, and publishes change events." },
        { id: "db", type: "sql_db", label: "File Metadata", col: 3, row: 0.3, note: "File tree, versions and chunk lists, sharded by user." },
        { id: "log", type: "stream", label: "Change Log", col: 3, row: 1.5, note: "Ordered per-user change events." },
        { id: "sync", type: "websocket", label: "Sync Service", col: 4, row: 1.5, note: "Holds device connections and pushes change notifications, so devices pull only what changed." },
        { id: "s3", type: "object_storage", label: "Chunk Storage", col: 2, row: 2.7, note: "Content-addressed chunks, deduplicated across users." },
      ],
      edges: [
        { from: "c", to: "lb", label: "metadata" },
        { from: "lb", to: "meta" },
        { from: "meta", to: "db" },
        { from: "meta", to: "log", label: "on commit", ratio: 0.1 },
        { from: "log", to: "sync" },
        { from: "c", to: "s3", label: "presigned chunks", ratio: 0.3 },
      ],
    },
    decisions: [
      {
        q: "Why chunk files?",
        a: "Chunks make uploads resumable, allow parallel transfers, and mean an edit re-uploads only the changed 4 MB blocks. Hashing chunks also deduplicates identical content across users.",
      },
      {
        q: "Why presigned URLs instead of uploading through the API?",
        a: "Streaming huge files through app servers wastes bandwidth and ties up workers. Presigned URLs send the bytes straight to object storage.",
      },
      {
        q: "How are conflicting edits resolved?",
        a: "Commits include the base version. If another device committed first, the server rejects the commit and the client saves a 'conflicted copy'. That's Dropbox's approach — simple, and it never loses data.",
      },
    ],
    deepDives: [
      { q: "How does a device catch up after being offline?", a: "It keeps a cursor (the last change sequence it saw) and asks for everything since it, then downloads only changed chunks." },
      { q: "How do you save storage?", a: "Content-addressed chunks give dedup for free, and cold versions can move to cheaper storage tiers." },
      { q: "Sharing?", a: "An ACL table maps (file_id, principal) → permission. Shared folders appear in each member's tree via references." },
    ],
    mistakes: [
      "Uploading whole files through the application servers.",
      "Re-uploading an entire file for a one-byte change.",
      "Having devices poll constantly instead of pushing change notifications.",
    ],
  },
  {
    slug: "distributed-cache",
    title: "Distributed Cache",
    tagline: "Design Redis / Memcached at scale",
    difficulty: "Medium",
    category: "Infrastructure",
    askedAt: ["Google", "Amazon", "Uber"],
    concepts: ["Consistent hashing", "Eviction (LRU)", "Replication & failover", "Cache-aside", "Hot keys"],
    functional: ["get(key) and set(key, value, ttl)", "Scale capacity by adding nodes", "Evict least-recently-used keys when full"],
    nonFunctional: ["Sub-millisecond reads", "Millions of ops/sec", "A node failure must not take the cache down"],
    estimates: [
      "1 TB of hot data on 64 GB nodes ≈ 16 shards, ×2 with replicas",
      "1M ops/sec ÷ ~100k ops/sec per node ≈ 10+ nodes for throughput",
      "Adding a node should move only ~1/N of keys",
    ],
    api: [
      { method: "GET", path: "get(key)", purpose: "Returns the value, or a miss" },
      { method: "PUT", path: "set(key, value, ttlSeconds)", purpose: "Stores a value, evicting LRU entries if the shard is full" },
      { method: "DELETE", path: "delete(key)", purpose: "Invalidates a key" },
    ],
    dataModel: [
      {
        entity: "Entry",
        store: "In-memory hash map + LRU list (per shard)",
        fields: "key → value, expires_at, LRU links",
        why: "A hash map gives O(1) lookups, and a doubly linked list gives O(1) LRU eviction.",
      },
      {
        entity: "Hash ring",
        store: "Config service (ZooKeeper / etcd)",
        fields: "virtual node → physical shard",
        why: "Every client agrees which shard owns a key, and membership changes propagate quickly.",
      },
    ],
    checkpoints: [
      {
        id: "entry",
        kind: "connection",
        title: "Clients reach the app through a load balancer",
        from: ["client"],
        to: ENTRY,
        hint: "Start at the edge.",
        why: "App servers are stateless, so they sit behind a load balancer.",
      },
      {
        id: "shards",
        kind: "component",
        title: "Cache split across several shards",
        types: ["cache"],
        min: 2,
        hint: "1 TB of hot data won't fit on one machine. How do you spread it?",
        why: "Partition keys across many cache nodes so capacity and throughput scale out.",
      },
      {
        id: "router",
        kind: "connection",
        title: "Consistent hashing routes each key to its shard",
        from: ENTRY,
        to: ["cache"],
        hint: "How does a request know which cache node holds its key?",
        why: "A consistent-hash ring maps keys to shards. Adding a node only moves about 1/N of the keys.",
      },
      {
        id: "backing",
        kind: "component",
        title: "Source of truth behind the cache",
        types: DB,
        hint: "What happens on a miss?",
        why: "Cache-aside: on a miss, read the database and populate the cache.",
      },
      {
        id: "miss",
        kind: "connection",
        title: "Misses fall through to the database",
        from: ["cache"],
        to: DB,
        hint: "Wire up the miss path.",
        why: "Only misses reach the database, which is the whole point of the cache.",
      },
    ],
    solution: {
      nodes: [
        { id: "c", type: "client", label: "Clients", col: 0, row: 1, note: "Callers doing get and set." },
        { id: "lb", type: "load_balancer", label: "Load Balancer", col: 1, row: 1, note: "Spreads requests over app servers." },
        { id: "app", type: "service", label: "App Servers", col: 2, row: 1, note: "Run the cache client library: they hash each key to find its shard." },
        { id: "ring", type: "load_balancer", label: "Consistent-Hash Ring", col: 3, row: 1, note: "Maps each key to one shard. Virtual nodes keep the load even." },
        { id: "a", type: "cache", label: "Cache Shard A", col: 4, row: 0, note: "Primary plus replica. LRU eviction when full.", config: { replicas: 2 } },
        { id: "b", type: "cache", label: "Cache Shard B", col: 4, row: 1, note: "Owns a different slice of the hash ring.", config: { replicas: 2 } },
        { id: "sh", type: "cache", label: "Cache Shard C", col: 4, row: 2, note: "A replica takes over within seconds if the primary fails.", config: { replicas: 2 } },
        { id: "db", type: "sql_db", label: "Source of Truth", col: 5, row: 1, note: "Serves only cache misses.", config: { replicas: 2 } },
      ],
      edges: [
        { from: "c", to: "lb" },
        { from: "lb", to: "app" },
        { from: "app", to: "ring" },
        { from: "ring", to: "a" },
        { from: "ring", to: "b" },
        { from: "ring", to: "sh" },
        { from: "a", to: "db", label: "miss" },
        { from: "b", to: "db", label: "miss" },
        { from: "sh", to: "db", label: "miss" },
      ],
    },
    decisions: [
      {
        q: "Why consistent hashing instead of key % N?",
        a: "With modulo, adding a node remaps almost every key and triggers a stampede of misses. Consistent hashing moves only about 1/N of the keys, and virtual nodes smooth out the imbalance.",
      },
      {
        q: "Why LRU?",
        a: "Recently used keys are the most likely to be used again. LRU is O(1) with a hash map plus a linked list, and it's the sensible default. LFU suits stable hot sets better.",
      },
      {
        q: "Replicate or not?",
        a: "Replicas give fast failover and spread read load, but writes must propagate. Replication is usually async, accepting slightly stale reads.",
      },
    ],
    deepDives: [
      { q: "Hot keys?", a: "Replicate the hot key across several shards (key#1..key#N), or add a small in-process cache in front for the hottest keys." },
      { q: "Cache stampede?", a: "When a popular key expires, many requests miss at once. Use request coalescing (single flight), jittered TTLs, or refresh-ahead." },
      { q: "Consistency with the database?", a: "Write to the database, then delete the cache key (not update it), and accept brief staleness. Stronger guarantees cost latency." },
    ],
    mistakes: [
      "Using hash % N, so every scale-up flushes the cache.",
      "No plan for a shard failure: no replica, so a whole slice of keys falls onto the database.",
      "Ignoring hot keys and stampedes.",
    ],
  },
  {
    slug: "instagram",
    title: "Photo Sharing",
    tagline: "Design Instagram",
    difficulty: "Medium",
    category: "Media",
    askedAt: ["Meta", "Amazon"],
    concepts: ["Media upload pipeline", "Thumbnails / async processing", "CDN delivery", "Feed generation", "Read-heavy scaling"],
    functional: ["Upload photos with captions", "Follow users", "View a home feed of followed users' photos", "Like and comment"],
    nonFunctional: ["Feed loads in < 200 ms", "Uploads can take seconds to process", "Photos must never be lost", "Heavily read-dominated"],
    estimates: [
      "500M DAU; ~100M photo uploads/day ≈ 1.2k uploads/sec",
      "~10 feed views per user per day ≈ 60k feed reads/sec",
      "2 MB original + 3 resized versions ≈ 3 MB × 100M ≈ 300 TB/day",
    ],
    api: [
      { method: "POST", path: "/photos", purpose: "Returns a presigned upload URL; commit with caption after upload" },
      { method: "GET", path: "/feed?cursor=", purpose: "Home feed page of post IDs, hydrated with image URLs" },
      { method: "POST", path: "/photos/{id}/likes", purpose: "Like a photo" },
    ],
    dataModel: [
      {
        entity: "Post",
        store: "Cassandra",
        fields: "post_id, author_id, caption, image_keys{thumb,medium,full}, created_at",
        why: "High write volume, read by ID for hydration, and easy to shard.",
      },
      {
        entity: "Image",
        store: "S3 + CDN",
        fields: "images/{post_id}/{size}.jpg",
        why: "Immutable blobs served globally from the edge.",
      },
      {
        entity: "Feed",
        store: "Redis list",
        fields: "feed:{user_id} → recent post IDs",
        why: "Precomputed timelines make feed reads a single lookup.",
      },
    ],
    checkpoints: [
      {
        id: "split",
        kind: "component",
        title: "Separate upload and feed services",
        types: ["service"],
        min: 2,
        hint: "Uploads are slow and rare, feed reads are fast and constant. One service for both?",
        why: "Split the write path (upload) from the read path (feed) so each scales on its own curve.",
      },
      {
        id: "blob",
        kind: "component",
        title: "Object storage for photos",
        types: ["object_storage"],
        hint: "Where do 300 TB a day of images go?",
        why: "Object storage holds the originals and resized versions.",
      },
      {
        id: "async",
        kind: "component",
        title: "Async image processing",
        types: ASYNC,
        hint: "Resizing into three sizes takes time. Should the upload wait for it?",
        why: "Enqueue a processing job, so the upload returns fast and workers generate thumbnails in the background.",
      },
      {
        id: "workers",
        kind: "connection",
        title: "Workers process the queue",
        from: ASYNC,
        to: ["worker"],
        hint: "What does the resizing?",
        why: "A worker pool consumes jobs and writes resized images back to storage.",
      },
      {
        id: "cdn",
        kind: "component",
        title: "CDN serves images",
        types: ["cdn"],
        hint: "Images are most of the bytes. Serve them from your servers?",
        why: "A CDN serves images near users, cutting latency and origin load.",
      },
      {
        id: "feed",
        kind: "component",
        title: "Precomputed feed cache",
        types: ["cache"],
        hint: "60k feed reads/sec — merge followers' posts on every read?",
        why: "Keep each user's timeline in Redis, so a feed read is one lookup.",
      },
    ],
    solution: {
      nodes: [
        { id: "c", type: "client", label: "Mobile App", col: 0, row: 2, note: "Uploads photos, scrolls the feed, and loads images from the CDN." },
        { id: "lb", type: "load_balancer", label: "Load Balancer", col: 1, row: 1.5, note: "Routes uploads and feed reads to different services." },
        { id: "post", type: "service", label: "Upload Service", col: 2, row: 0.5, note: "Saves the post, puts the original in storage, and enqueues a resize job." },
        { id: "posts", type: "nosql_db", label: "Posts DB", col: 3, row: -0.3, note: "Post metadata, sharded by post ID." },
        { id: "q", type: "queue", label: "Processing Queue", col: 3, row: 0.8, note: "One job per upload." },
        { id: "w", type: "worker", label: "Image Resizers", col: 4, row: 0.8, note: "Generate thumbnail, medium and full sizes, and strip metadata." },
        { id: "s3", type: "object_storage", label: "Photo Storage", col: 5, row: 1.8, note: "Originals and resized versions. Origin for the CDN." },
        { id: "feed", type: "service", label: "Feed Service", col: 2, row: 2.5, note: "Reads the precomputed timeline and hydrates the posts." },
        { id: "fc", type: "cache", label: "Feed Cache", col: 3, row: 2.5, note: "feed:{user} → recent post IDs, filled by fan-out on write." },
        { id: "cdn", type: "cdn", label: "Image CDN", col: 1, row: 3.6, note: "Serves images from the edge. Popular photos almost never hit origin." },
      ],
      edges: [
        { from: "c", to: "lb" },
        { from: "lb", to: "post", ratio: 1 },
        { from: "lb", to: "feed", ratio: 10 },
        { from: "post", to: "posts", label: "save" },
        { from: "post", to: "s3", label: "original" },
        { from: "post", to: "q", label: "resize job" },
        { from: "q", to: "w" },
        { from: "w", to: "s3", label: "3 sizes", ratio: 3 },
        { from: "feed", to: "fc", label: "timeline" },
        { from: "feed", to: "posts", label: "hydrate", ratio: 1 },
        { from: "c", to: "cdn", label: "images" },
        { from: "cdn", to: "s3", label: "miss" },
      ],
    },
    decisions: [
      {
        q: "Why process images asynchronously?",
        a: "Resizing takes hundreds of milliseconds per image. Doing it in the request makes uploads slow and couples upload capacity to CPU-heavy work.",
      },
      {
        q: "How is the feed built?",
        a: "Fan-out on write for normal accounts (push post IDs into followers' feed caches), merging celebrity posts at read time — the same hybrid as the news feed.",
      },
      {
        q: "Why store several image sizes?",
        a: "A phone grid needs thumbnails, not 12 MP originals. Pre-sized variants cut bandwidth and load time dramatically.",
      },
    ],
    deepDives: [
      { q: "Upload directly to storage?", a: "Yes. Presigned URLs let the app upload straight to object storage, and the service just records the post." },
      { q: "Likes at scale?", a: "Count likes asynchronously: write like events to a stream, aggregate the counters, and cache the totals." },
      { q: "Explore / recommendations?", a: "A separate offline pipeline ranks candidate posts, and the explore service serves the precomputed results." },
    ],
    mistakes: [
      "Serving images from the application servers instead of a CDN.",
      "Resizing images inside the upload request.",
      "Computing the feed from scratch on every read.",
    ],
  },
  {
    slug: "live-comments",
    title: "Live Comments",
    tagline: "Design live comments on a livestream",
    difficulty: "Medium",
    category: "Social",
    askedAt: [],
    concepts: ["Pub/sub fan-out", "WebSockets / SSE", "Hot partitions", "Recent-history cache"],
    functional: ["Viewers post comments on a live video", "Every viewer sees new comments in near real time", "Late joiners see recent comments"],
    nonFunctional: ["Delivery within ~1 s", "Streams with millions of concurrent viewers", "Losing an occasional comment is acceptable, reordering isn't"],
    estimates: [
      "Popular stream: 1M viewers, ~5k comments/sec",
      "Fan-out: 5k comments × 1M viewers — so batch and sample, don't send every comment to everyone",
      "Each gateway holds ~100k connections → 10+ gateways per big stream",
    ],
    api: [
      { method: "POST", path: "/streams/{id}/comments", purpose: "Post a comment" },
      { method: "WS", path: "/streams/{id}/live", purpose: "Subscribe to new comments (SSE also works)" },
      { method: "GET", path: "/streams/{id}/comments?before=", purpose: "Recent history for late joiners" },
    ],
    dataModel: [
      {
        entity: "Comment",
        store: "Cassandra",
        fields: "stream_id (partition), comment_id (time-sortable), user_id, text",
        why: "Append-heavy writes, read back by stream in time order.",
      },
      {
        entity: "Recent comments",
        store: "Redis list",
        fields: "recent:{stream_id} → last 200 comments",
        why: "Late joiners load recent history from memory, not the database.",
      },
    ],
    checkpoints: [
      {
        id: "ws",
        kind: "component",
        title: "Persistent push connections",
        types: ["websocket"],
        hint: "How do a million viewers see a comment within a second without polling?",
        why: "Viewers hold WebSocket or SSE connections to gateway servers, which push new comments.",
      },
      {
        id: "pubsub",
        kind: "component",
        title: "Pub/sub between writers and gateways",
        types: ASYNC,
        hint: "A comment arrives on one server, but viewers are spread over hundreds. How does it reach all of them?",
        why: "Publish each comment to a per-stream channel, and every gateway with viewers of that stream subscribes.",
      },
      {
        id: "fanout",
        kind: "connection",
        title: "Pub/sub feeds the push servers",
        from: ASYNC,
        to: ["websocket"],
        hint: "Connect the channel to the servers holding viewer connections.",
        why: "Gateways consume the stream's channel and forward comments to their local viewers.",
      },
      {
        id: "store",
        kind: "component",
        title: "Durable comment store",
        types: DB,
        hint: "Where do comments live after the stream ends?",
        why: "A wide-column store keeps comments partitioned by stream for replays and moderation.",
      },
      {
        id: "recent",
        kind: "component",
        title: "Recent comments cache",
        types: ["cache"],
        hint: "Someone joins mid-stream. Should they query the database?",
        why: "Keep the last few hundred comments per stream in Redis for instant history.",
      },
    ],
    solution: {
      nodes: [
        { id: "c", type: "client", label: "Viewers", col: 0, row: 1, note: "Most just watch; a few percent post comments." },
        { id: "lb", type: "load_balancer", label: "Load Balancer", col: 1, row: 1, note: "Spreads both posting and history requests." },
        { id: "api", type: "service", label: "Comment API", col: 2, row: 1, note: "Validates and moderates comments, stores them, and publishes them to the stream's channel." },
        { id: "recent", type: "cache", label: "Recent Comments", col: 3, row: 0, note: "The last 200 comments per stream, for late joiners." },
        { id: "db", type: "nosql_db", label: "Comments Store", col: 3, row: 2, note: "Durable comment history, partitioned by stream." },
        { id: "bus", type: "stream", label: "Comment Pub/Sub", col: 3, row: 1, note: "A channel per stream. Gateways subscribe to the streams their viewers watch." },
        { id: "push", type: "websocket", label: "Push Gateways", col: 4, row: 1, note: "Hold viewer connections and batch comments into ~1s pushes." },
      ],
      edges: [
        { from: "c", to: "lb" },
        { from: "lb", to: "api" },
        { from: "api", to: "recent", label: "history / append" },
        { from: "api", to: "db", label: "persist", ratio: 0.1 },
        { from: "api", to: "bus", label: "publish", ratio: 0.1 },
        { from: "bus", to: "push" },
      ],
    },
    decisions: [
      {
        q: "WebSockets or SSE?",
        a: "Comments flow mostly server→client, so SSE is simpler and works over plain HTTP. Posting can be a normal POST. WebSockets are fine if you also need client→server streaming.",
      },
      {
        q: "Why pub/sub instead of the API calling gateways directly?",
        a: "The API doesn't know which of hundreds of gateways hold viewers of a stream. With pub/sub, gateways subscribe to what they need, and adding gateways needs no coordination.",
      },
      {
        q: "Do all 5k comments/sec reach every viewer?",
        a: "No. Nobody can read that. Gateways batch and sample (e.g. about 20 per second per viewer, prioritizing friends and creators), which cuts fan-out by orders of magnitude.",
      },
    ],
    deepDives: [
      { q: "Hot stream?", a: "One huge stream can overwhelm a single partition. Shard its channel into N sub-channels and have gateways subscribe to all of them." },
      { q: "Ordering?", a: "Time-sortable IDs (e.g. Snowflake) let clients order comments, even if batches arrive slightly out of order." },
      { q: "Moderation?", a: "Run fast automated filters synchronously before publishing, and deeper review asynchronously, with takedown events published to the same channel." },
    ],
    mistakes: [
      "Polling for new comments every second from millions of clients.",
      "Having the API server loop over every connected viewer.",
      "Sending every comment to every viewer instead of batching or sampling.",
    ],
  },
  {
    slug: "notification-system",
    title: "Notification System",
    tagline: "Design a push / email / SMS notification service",
    difficulty: "Medium",
    category: "Infrastructure",
    askedAt: [],
    concepts: ["Queues per channel", "Retries & dead-letter queues", "User preferences", "Rate limiting & dedup", "Third-party providers"],
    functional: ["Other services send notifications to users", "Push, email and SMS channels", "Respect user preferences and quiet hours", "Track delivery status"],
    nonFunctional: ["At-least-once delivery, deduplicated", "A slow email provider must not delay push notifications", "Handle bursts like breaking news"],
    estimates: [
      "10M push + 5M email + 1M SMS per day ≈ 200/sec average, 10× in bursts",
      "Providers (APNs, FCM, SES, Twilio) have their own rate limits",
      "Delivery log ≈ 16M rows/day",
    ],
    api: [
      { method: "POST", path: "/notifications", purpose: "Body { userId, template, data, channels?, idempotencyKey } → 202 Accepted" },
      { method: "PUT", path: "/users/{id}/preferences", purpose: "Opt in or out per channel and category, and set quiet hours" },
      { method: "GET", path: "/notifications/{id}", purpose: "Delivery status per channel" },
    ],
    dataModel: [
      {
        entity: "Preferences",
        store: "PostgreSQL + Redis cache",
        fields: "user_id, channel, category, enabled, quiet_hours",
        why: "Read on every notification, so it's cached. Rarely written.",
      },
      {
        entity: "Delivery log",
        store: "Cassandra",
        fields: "notification_id, user_id, channel, status, attempts, ts",
        why: "High-volume, append-only status tracking.",
      },
    ],
    checkpoints: [
      {
        id: "entry",
        kind: "connection",
        title: "Callers hit a gateway",
        from: ["client"],
        to: ENTRY,
        hint: "Many internal services call you. What sits at the front door?",
        why: "An API gateway authenticates callers and rate-limits noisy ones.",
      },
      {
        id: "queues",
        kind: "component",
        title: "Queues decouple sending",
        types: ASYNC,
        hint: "Should the caller wait while you talk to Apple's push service?",
        why: "Accept the request, enqueue it, and return 202. Queues absorb bursts, and retries happen in the background.",
      },
      {
        id: "workers",
        kind: "component",
        title: "Separate workers per channel",
        types: ["worker"],
        min: 2,
        hint: "Email providers are slow today. Should that delay push notifications?",
        why: "A queue and worker pool per channel isolate failures and let each scale to its provider's limits.",
      },
      {
        id: "consume",
        kind: "connection",
        title: "Workers consume the queues",
        from: ASYNC,
        to: ["worker"],
        hint: "Connect queues to their workers.",
        why: "Workers pull, call the provider, and retry with backoff. Poison messages go to a dead-letter queue.",
      },
      {
        id: "prefs",
        kind: "component",
        title: "Preferences store",
        types: DB,
        hint: "How do you know the user turned off marketing emails?",
        why: "Check preferences (cached) before enqueueing anything.",
      },
    ],
    solution: {
      nodes: [
        { id: "c", type: "client", label: "Internal Services", col: 0, row: 1.5, note: "Order service, social graph and others call one API to notify users." },
        { id: "gw", type: "api_gateway", label: "API Gateway", col: 1, row: 1.5, note: "Authenticates callers and rate-limits noisy ones." },
        { id: "ns", type: "service", label: "Notification Service", col: 2, row: 1.5, note: "Dedupes by idempotency key, checks preferences, renders templates, and routes to channel queues." },
        { id: "pc", type: "cache", label: "Preferences Cache", col: 3, row: -0.2, note: "User settings, read on every send." },
        { id: "prefs", type: "sql_db", label: "Preferences DB", col: 4, row: -0.2, note: "Source of truth for opt-ins and quiet hours." },
        { id: "qp", type: "queue", label: "Push Queue", col: 3, row: 1, note: "Push notifications via APNs and FCM." },
        { id: "qe", type: "queue", label: "Email Queue", col: 3, row: 2, note: "Emails via SES or SendGrid." },
        { id: "qs", type: "queue", label: "SMS Queue", col: 3, row: 3, note: "SMS via Twilio." },
        { id: "wp", type: "worker", label: "Push Workers", col: 4, row: 1, note: "Call APNs and FCM, retrying with backoff.", config: { replicas: 4, capacity: 300 } },
        { id: "we", type: "worker", label: "Email Workers", col: 4, row: 2, note: "Send emails within the provider's rate limits." },
        { id: "wsm", type: "worker", label: "SMS Workers", col: 4, row: 3, note: "Send SMS, the most expensive channel." },
        { id: "log", type: "nosql_db", label: "Delivery Log", col: 5, row: 2, note: "Status per notification per channel." },
      ],
      edges: [
        { from: "c", to: "gw" },
        { from: "gw", to: "ns" },
        { from: "ns", to: "pc", label: "check prefs" },
        { from: "ns", to: "prefs" },
        { from: "ns", to: "qp", ratio: 0.6 },
        { from: "ns", to: "qe", ratio: 0.3 },
        { from: "ns", to: "qs", ratio: 0.1 },
        { from: "qp", to: "wp" },
        { from: "qe", to: "we" },
        { from: "qs", to: "wsm" },
        { from: "wp", to: "log", label: "status" },
        { from: "we", to: "log", label: "status" },
        { from: "wsm", to: "log", label: "status" },
      ],
    },
    decisions: [
      {
        q: "Why one queue per channel?",
        a: "Channels fail independently: email can back up without delaying push. Separate queues also let each worker pool respect its provider's rate limit.",
      },
      {
        q: "How do you avoid duplicate notifications?",
        a: "Callers send an idempotency key. The service records it (with a TTL) and ignores repeats, and workers dedupe on retry too.",
      },
      {
        q: "What happens when a provider is down?",
        a: "Workers retry with exponential backoff. After N attempts the message moves to a dead-letter queue for inspection or replay, so nothing is silently dropped.",
      },
    ],
    deepDives: [
      { q: "Bursts (breaking news to 50M users)?", a: "Fan out in batches through the queue. Workers drain at provider limits while the queue absorbs the spike." },
      { q: "Quiet hours and priorities?", a: "Delay low-priority messages with a scheduled queue or visibility timeout, and let critical ones (2FA codes) skip it." },
      { q: "Analytics?", a: "Stream delivery and open events to a data pipeline for per-template metrics." },
    ],
    mistakes: [
      "Calling providers synchronously inside the caller's request.",
      "One shared queue for all channels, so a slow provider blocks everything.",
      "No retries or dead-letter queue, so failures vanish silently.",
    ],
  },
];
